### ISSUE TITLE
Changes from PR https://github.com/dotnet/docs.zh-cn/pull/64 got reverted

### ISSUE THREAD

**Issue by vicancy** [dotnet/docs.zh-cn#106]
Hi @gosali, for file https://github.com/dotnet/docs.zh-cn/commits/live/docs/csharp/discards.md, on Oct 16, 2017 a PR was merged to more accurately translate `discard`, however, on Dec 1, 2017, commit from @olprod reverted that change back to the NOT accurate one.

**Comment by herohua** [comment]
@SunnyDeng @SonjaSaltzman to be aware of this issue

**Comment by SunnyDeng** [comment]
@herohua @vicancy Thanks a lot! Your PR has been merged, though the final term translation is TBD, but I will involve you whenever it is ready. Close ISSUE as the action item is defined.
