### ISSUE TITLE
将"Discards"翻译成 "放弃"太过于生硬

### ISSUE THREAD

**Issue by zhipu123** [dotnet/docs.zh-cn#107]
将"Discards"翻译成 "放弃"太过于生硬,让读者容易摸不到头脑
比如 

> 放弃 - C# 指南
> 从 C# 7 开始，C# 支持放弃，这是一种在应用程序代码中人为取消使用的临时虚拟变量。 放弃相当于未赋值的变量；它们没有值。 因为只有一个放弃变量，并且甚至不为该变量分配存储空间，所以放弃可减少内存分配。 因为它们使代码的意图清楚，增强了其可读性和可维护性。

认为比较好的翻译方式应该是
空占位符, 无作用变量名 等

**Comment by zhipu123** [comment]
Created PR https://github.com/dotnet/docs.zh-cn/pull/108

**Comment by ZSkycat** [comment]
以后没有 放弃 C# 指南了，好可惜 +_,+

**Comment by CeciAc** [comment]
尊敬的 @zhipu123 ：你好，谢谢你的反馈和建议！
我们将在正式版中采纳你的建议，并将在下一轮本地化发布时重新发布相应文章。
Microsoft C&E 本地化团队敬上
