### ISSUE TITLE
“小数”按照格式应该是decimal

### ISSUE THREAD

**Issue by luo4neck** [dotnet/docs.zh-cn#112]
https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/value-types-table.md

**Comment by CeciAc** [comment]
尊敬的 @luo4neck ：你好，谢谢你的反馈和建议！ 
		
我们将在正式版中采纳你的建议，并将在下一轮本地化发布时重新发布相应文章。 
		
Microsoft C&E 本地化团队敬上
