### ISSUE TITLE
A Link returns 404

### ISSUE THREAD

**Issue by KaiqiYang94** [dotnet/docs.zh-cn#117]
The hyperlink "Contributing guide" in the README.md is returning 404.
It points to "https://github.com/dotnet/docs.zh-cn/blob/live/CONTRIBUTING.md".

**Comment by mairaw** [comment]
@nokura, @carolinacmoravia edited the readme on our repo to solve this issue. Should we just copy the new readme from English into the Loc repos?

**Comment by CeciAc** [comment]
Assigning to @nokura to check this issue.

**Comment by nokura** [comment]
Hello @KaiqiYang94 
Thank you for your feedback. We have unified contribution guide for docs.microsoft.com. Will you refer to this page? https://docs.microsoft.com/contribute/
Kind regards,
Microsoft DOCS International Team

**Comment by KaiqiYang94** [comment]
Hey Nobuko,

No problem. PR created.

Best Regards,
Kaiqi
