### ISSUE TITLE
maybe a syntax error

### ISSUE THREAD

**Issue by CFhM** [dotnet/docs.zh-cn#129]
`where` as a member func  of IEnumrable<T>，as para might be `this IEnumrable<T> source` ?

**Comment by imba-tjd** [comment]
给个链接啊……你这让别人怎么找

**Comment by CeciAc** [comment]
你好，@CFhM
感谢你的反馈。 

请提供您发现此问题的网址。

深深的祝福， 
Microsoft DOCS International Team

**Comment by CFhM** [comment]
https://docs.microsoft.com/zh-cn/dotnet/csharp/delegates-patterns
[cid:image001.png@01D3E955.61412E70]
如果是按照.Where的形式调用的话

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by CFhM** [comment]
也可能是个人理解不够深入，如果说错了请海涵

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by imba-tjd** [comment]
Personally I agree with you.

**Comment by CFhM** [comment]
[cid:image001.png@01D3E970.194A8740]
怕不是agree with 我很菜这个命题？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by imba-tjd** [comment]
不是啦:joy:,不要版聊。Please don't spam.

**Comment by CeciAc** [comment]
你好，@CFhM 

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/5318。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 

Microsoft DOCS International Team
