### ISSUE TITLE
html error

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs.zh-cn#131]
In https://docs.microsoft.com/zh-cn/dotnet, the `EF Core` link is not accessible.

![image](https://user-images.githubusercontent.com/24759802/40089027-4fd0b844-58dc-11e8-9ebc-0b9c9225550e.png)

**Comment by DavidPrio** [comment]
Hello, @imba-tjd ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team
