### ISSUE TITLE
Colon within emphasis indicators followd with Chinese characters won't be rendered.

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs.zh-cn#136]
If a colon is on the inner boundary of emphasis indicators **and** the outside character is neither punctuation nor blank space, markdown will not render it.

For example:

**test:**test

**测试：**测试

It's natural to add a blank space after an English colon, but Chinese colon is diffrent. We usually don't add spaces after punctuation.

On solution is move the colon out of asterisks, another is add a space. Currently there are both of them, and lots of unfixed exist. 

It affects all Simplified-Chinese repositories including this one and also Traditional-Chinese repositories if they use emphasis indicators like that. I think it needs to be specified.

**Comment by CeciAc** [comment]
Hello, @imba-tjd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @imba-tjd

Can you please provide and example of a live URL where you spotted this?

Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
@CeciAc 
Solution one: https://github.com/aspnet/EntityFramework.Docs.zh-cn/pull/6/files#diff-7992eff97d38b05ef2e5d29d04e5b9deR123

Solution two: https://github.com/dotnet/docs.zh-cn/commit/31f7fb35c30c148e5ee70d214255629a47d98820#diff-4ffc920b24cd452aeb08b37ac70a0025R21

unfixed: https://github.com/dotnet/docs.zh-cn/blame/live/docs/framework/additional-apis/_autoredirects.md#L40

But now I see many unfixed issues are translated by machine, so it's not so important as I thought.

**Comment by CeciAc** [comment]
Hello, @imba-tjd 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://github.com/dotnet/docs.zh-cn/blame/live/docs/framework/additional-apis/_autoredirects.md#L40. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
