### ISSUE TITLE
translate of “tuple”

### ISSUE THREAD

**Issue by lover299** [dotnet/docs.zh-cn#139]
文档中部分翻译“元祖”是不是翻译错了，其他部分都为“元组“（Tuple）

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [元组类型 - C# 指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/tuples)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tuples.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment]
You can create a PR.

**Comment by CeciAc** [comment]
你好，@lover299 

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/tuples。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福，
