### ISSUE TITLE
下载C#教程中的所有控制台程序的演示源代码？

### ISSUE THREAD

**Issue by globalhqw** [dotnet/docs.zh-cn#140]
如何下载这部分C#教程中的所有控制台程序的演示源代码呢？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a4a28322-944d-73c3-177c-d9bec577c08b
* Version Independent ID: 15ce52df-1eb1-7743-8440-dbef3169487c
* Content: [控制台应用程序](https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/console-teleprompter#feedback)
* Content Source: [docs/csharp/tutorials/console-teleprompter.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tutorials/console-teleprompter.md)
* Product: **.net-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
你好，@globalhqw

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team 

@nokura
