### ISSUE TITLE
在run里面

### ISSUE THREAD

**Issue by wechS** [dotnet/docs.zh-cn#143]
如果确定RichTextBox中某个字符的位置，特别是在有格式的文字

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 78742fe3-13f8-1868-9324-404652365e5b
* Version Independent ID: bdaed469-a620-95d5-a33d-170d38c07082
* Content: [以编程方式更改 RichTextBox 中的选定内容](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/controls/change-selection-in-a-richtextbox-programmatically)
* Content Source: [docs/framework/wpf/controls/change-selection-in-a-richtextbox-programmatically.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/controls/change-selection-in-a-richtextbox-programmatically.md)
* Product: **.net-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@wechS
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
你好，@wechS

您能否向我们提供有关此问题的更多信息？

谢谢

**Comment by LisandroSu** [comment]
你好，@wechS

感谢你的反馈。

我们没有足够的信息来处理此问题。 我们正在结束这个问题。

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。

深深的祝福，
Microsoft DOCS国际团队
