### ISSUE TITLE
Will be support epub?

### ISSUE THREAD

**Issue by xiekeyi98** [dotnet/docs.zh-cn#146]
I want to read some tutorials using my cell phone in the bus or metro , therefor , I was wondering if you could support .epub or .mobi in the future?

**Comment by CeciAc** [comment]
Hello, @xiekeyi98,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

@mairaw
