### ISSUE TITLE
"switch 语句" 示例代码报错, 建议更换

### ISSUE THREAD

**Issue by hwhois** [dotnet/docs.zh-cn#153]
"switch 语句" 示例代码 中
 Console.WriteLine($"{n}  arguments"); 在命令行编译时报错: error CS1056: 意外的字符“$”.
建议修改为:  Console.WriteLine(n + " arguments")

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 017f9566-a4df-e294-d6e8-da9252469ca9
* Version Independent ID: 6665f9d5-24bf-ac0d-62f5-d63ed53132ed
* Content: [C# 语句 - C# 语言介绍](https://docs.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/statements#feedback)
* Content Source: [docs/csharp/tour-of-csharp/statements.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tour-of-csharp/statements.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment]
It is called [string interpolation](https://docs.microsoft.com/zh-cn/dotnet/csharp/whats-new/csharp-6#string-interpolation).

**Comment by DavidPrio** [comment]
你好，@hwhois
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by gosali** [comment]
Issue moved to [dotnet/docs #6043](https://github.com/dotnet/docs/issues/6043) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gosali** [comment]
你好，@<参与者的 GITHUB 名>  

 

非常感谢你的参与。你的反馈与原始文档有关。  

 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 -https://github.com/dotnet/docs/issues/6043。  

 

非常感谢你对我们的文章作出的贡献。   

 

 

深深的祝福，  

Microsoft DOCS International Team

**Comment by hwhois** [comment]
谢谢, 楼主上, 但C# 6要怎么用捏? csc 编译一直报错(netformwork4.01) : 意外字符: "$"

**Comment by imba-tjd** [comment]
![default](https://user-images.githubusercontent.com/24759802/41642832-0ed3b59a-749c-11e8-9e08-6810497f6975.png)

**Comment by jing8956** [comment]
@hwhois 内插字符串语法正是 C#6.0 中的新增功能，
使用 C#6.0 语法需要确保 Visual Studio 版本最低为 2015，
该语法应该与框架无关，我在.Net Framework 4.0项目里也能使用这个语法正常编译。

**Comment by imba-tjd** [comment]
@jing8956 好吧，貌似是这样的……我测试的也是可以……
