### ISSUE TITLE
请尽快更新中文文档

### ISSUE THREAD

**Issue by FOWind** [dotnet/docs.zh-cn#156]
ML.net的中文文档缺失，请尽快上传机器翻译的中文文档，

**Comment by gosali** [comment]
您好，谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？ 

 深深的祝福，  

Microsoft DOCS International Team

**Comment by gosali** [comment]
您好，谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？

深深的祝福， 
CC @Sara-nicolini, @nokura 
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
@gosali He requested for ML.NET machine translation. It has been finished.

**Comment by nokura** [comment]
Hello @FOWind 
Thank you for your feedback.
If you are asking us to localize the topics under this section, we have already published zh-cn localized version. 
https://docs.microsoft.com/zh-cn/dotnet/machine-learning/.

Microsoft DOCS International Team

**Comment by DavidPrio** [comment]
Hello @FOWind
Thank you for your feedback.
If you are asking us to localize the topics under this section, we have already published zh-cn localized version.
https://docs.microsoft.com/zh-cn/dotnet/machine-learning/.

Microsoft DOCS International Team 
#please-translate

**Comment by DavidPrio** [comment]
@FOWind，您好！
非常感谢您的反馈。
如果您想要查看该部分所有主题的本地化版本，请参阅此链接查看简体中文版：
https://docs.microsoft.com/zh-cn/dotnet/machine-learning/
Microsoft DOCS International Team
