### ISSUE TITLE
net core无法删除

### ISSUE THREAD

**Issue by Hansdas** [dotnet/docs.zh-cn#157]
[在此处输入反馈]
因为之前的dll删掉了，所以web里面的项目有个节点一直删不了
![image](https://user-images.githubusercontent.com/35918028/41827834-3ebaf892-7864-11e8-9a5e-40f4e6c45bbe.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 850b3e30-8b0c-e9a0-df2d-45b82085fccc
* Version Independent ID: 695ff940-58a2-69d5-f160-76a0b30f9b8e
* Content: [dotnet remove reference 命令 - .NET Core CLI](https://docs.microsoft.com/zh-cn/dotnet/core/tools/dotnet-remove-reference)
* Content Source: [docs/core/tools/dotnet-remove-reference.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/tools/dotnet-remove-reference.md)
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by gosali** [comment]
你好，@Hansdas  
 
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。  
 
请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。  
 
若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。  

非常感谢你对我们的文章作出的贡献。   
 
深深的祝福，  
@nokura 
Microsoft DOCS International Team
