### ISSUE TITLE
延迟初始化还是迟缓初始化？

### ISSUE THREAD

**Issue by gqqnbig** [dotnet/docs.zh-cn#159]
[docs/framework/performance/lazy-initialization.md](docs/framework/performance/lazy-initialization.md) 的标题是延迟初始化，但正文里说的是迟缓初始化，请问哪个术语是正确的？

传统上延迟初始化的用法比较普遍。

**Comment by gosali** [comment]
你好，@gqqnbig

感谢你的反馈。  

我们正在积极查看你的评论，并会很快地再次和你取得联系。  

深深的祝福，  

Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
你好，@gqqnbig

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：XXX。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
