### ISSUE TITLE
awesome!

### ISSUE THREAD

**Issue by imwangji** [dotnet/docs.zh-cn#162]
awesome!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8b514dfb-f00b-8ac3-4027-7a28770f959e
* Version Independent ID: 7db3af08-9406-10da-76a1-1f8db30d1d2d
* Content: [“Hello World”交互教程 - C# 快速入门](https://docs.microsoft.com/zh-cn/dotnet/csharp/quick-starts/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/hello-world.yml](https://github.com/dotnet/docs.zh-cn/blob/live-sxs/docs/csharp/quick-starts/hello-world.yml)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
你好，@imwangji

非常感谢你提供反馈。很高兴我们的文档满足你的期望。
 
欢迎提供宝贵的反馈，以便我们继续改进体验。
 
 
 
深深的祝福，
 
Microsoft DOCS International   Team

**Comment by singi2016cn** [comment]
very helpful, thank you !!!
