### ISSUE TITLE
无法安装Net framework 3.5 Service pack 1

### ISSUE THREAD

**Issue by Yesterday1** [dotnet/docs.zh-cn#170]
之前我有试过以上安装错误等一系列解决办法，但唯独我台电脑Win10连Net framework 3.5装不了而且按照以上所说的（错误码：0x800F0922）的解决文章，我也是找不到相关的文件，但同时也要求我安装Net framework 2,3,4版本软件，我应该怎么做呢？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [在 Windows 10、Windows 8.1 和 Windows 8 上安装 .NET Framework 3.5](https://docs.microsoft.com/zh-cn/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/install/dotnet-35-windows-10.md)
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by Yesterday1** [comment]
现在我除了SDK这个软件以外我什么也没有安装，就整天在提示需要我安装Net framework 2、3、4，尝试安装Net framework 4也失败了（那里显示有一个高于这个版本的软件），我这一台电脑是最近才安装Win10的安全性能非常好。

**Comment by LisandroSu** [comment]
你好，@Yesterday1 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。
 
请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。
 
若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。
 
非常感谢你对我们的文章作出的贡献。
 
深深的祝福，
