### ISSUE TITLE
机器翻译错误很多

### ISSUE THREAD

**Issue by cmsax** [dotnet/docs.zh-cn#174]
一些机器翻译的内容明显存在错误，却没有提供途径以众包方式更新翻译，或者直接允许用户对某一个翻译提供修改意见。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e74bccb0-6965-36db-f998-8e82188f080e
* Version Independent ID: 99af1ae8-9e4a-d5db-5dd4-c5bad9925818
* Content: [作为一类值的函数 (F#)](https://docs.microsoft.com/zh-cn/dotnet/fsharp/introduction-to-functional-programming/functions-as-first-class-values#store-the-value-in-a-data-structure)
* Content Source: [docs/fsharp/introduction-to-functional-programming/functions-as-first-class-values.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/fsharp/introduction-to-functional-programming/functions-as-first-class-values.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
你好，@cmsax

感谢你的反馈。有问题的页面是采用机器翻译的，因此不一定容易理解。我们最近在右侧添加了“阅读英文版”选项，无需更改语言设置即可切换到的英文版。 

您可以点击此处编辑文章：
![image](https://user-images.githubusercontent.com/39163942/43474674-e7521734-94c9-11e8-927e-8ad254f811d9.png)

深深的祝福， 
Microsoft DOCS International Team
