### ISSUE TITLE
无法安装.NET 3.5

### ISSUE THREAD

**Issue by SmallOyster** [dotnet/docs.zh-cn#185]
显示“灾难性错误，错误码：0x8000FFFF”

**Comment by LisandroSu** [comment]
您好，@SmallOyster

感谢您的反馈意见。 我们需要更多信息才能处理这个问题。 您能否提供更详细的说明和需要修改/修复的具体行？ 以及您关注的文档。
 
亲切的问候，
Microsoft DOCS国际团队

**Comment by LisandroSu** [comment]
你好，@SmallOyster
 
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。
 
请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。
 
若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。
 
非常感谢你对我们的文章作出的贡献。

深深的祝福，
Microsoft DOCS International Team
