### ISSUE TITLE
字段初始值无法引用非静态字段

### ISSUE THREAD

**Issue by wengxk** [dotnet/docs.zh-cn#188]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 532cc73d-1f86-1c11-ddcb-88d9aae4664d
* Version Independent ID: a4d69158-c435-5d5e-23be-59d60c3c4fb2
* Content: [可互操作的对象引用](https://docs.microsoft.com/zh-cn/dotnet/framework/wcf/feature-details/interoperable-object-references)
* Content Source: [docs/framework/wcf/feature-details/interoperable-object-references.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wcf/feature-details/interoperable-object-references.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gosali** [comment]
@wengxk ,

您好，谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？ 

深深的祝福，

**Comment by LisandroSu** [comment]
@wengxk ,

您好，谢谢您的反馈。我们需要更多信息才能处理这个问题；您能否提供更加详细的说明？

深深的祝福，

**Comment by LisandroSu** [comment]
@wengxk  您好：

再次感謝您的寶貴意見。

很遺憾至今我們仍未收到您的進一步資訊，所以無法處理您的意見反應。目前我們會先將此 GitHub 問題結案處理，期望您日後能夠再提供更多的意見。

順頌時祺
Microsoft DOCS International Team
