### ISSUE TITLE
Code lack

### ISSUE THREAD

**Issue by hjkl950217** [dotnet/docs.zh-cn#193]
ctrl+f搜索“对于每个类型实参，使用 IsGenericParameter 属性确定它是类型形参（例如，在泛型类型定义中），还是为类型形参指定的类型（例如，在构造类型中）。” 其中的代码少了一部分。
参考：https://docs.microsoft.com/zh-cn/dotnet/api/system.type.isgenericparameter?view=netframework-4.7.2

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3eb2faee-ed39-b589-4d6e-09fa6fb8e5b1
* Version Independent ID: 38e9f433-d8f5-2db2-6581-830121bbf216
* Content: [如何：使用反射检查和实例化泛型类型](https://docs.microsoft.com/zh-cn/dotnet/framework/reflection-and-codedom/how-to-examine-and-instantiate-generic-types-with-reflection)
* Content Source: [docs/framework/reflection-and-codedom/how-to-examine-and-instantiate-generic-types-with-reflection.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/reflection-and-codedom/how-to-examine-and-instantiate-generic-types-with-reflection.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
你好，@hjkl950217

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by LisandroSu** [comment]
你好，@hjkl950217

我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by LisandroSu** [comment]
你好，@hjkl950217

再次感谢你的评论。

很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。

顺祝商祺！
Microsoft DOCS 国际团队
