### ISSUE TITLE
This is a issue

### ISSUE THREAD

**Issue by xzssws** [dotnet/docs.zh-cn#197]
如果能在这里加入一个示例的超链接 就更好了

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 22466224-0284-7845-1000-f76d59d09565
* Version Independent ID: 1bbd1b54-8042-02ca-28f8-ddb306586364
* Content: [使用应用程序域](https://docs.microsoft.com/zh-cn/dotnet/framework/app-domains/use)
* Content Source: [docs/framework/app-domains/use.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/app-domains/use.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by imba-tjd** [comment]
底下全是示例啊
![default](https://user-images.githubusercontent.com/24759802/45277045-44905980-b4f8-11e8-897a-7a21247499e9.png)

**Comment by LisandroSu** [comment]
你好，@xzssws，

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by LisandroSu** [comment]
你好，@xzssws，

我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by LisandroSu** [comment]
你好，@xzssws
再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。
顺祝商祺！
Microsoft DOCS 国际团队
