### ISSUE TITLE
Where Is Contribution Guide

### ISSUE THREAD

**Issue by lextm** [dotnet/docs.zh-cn#2]
Thanks for making this repo public at last.

I hope a contribution guide can be finalized soon so that the Chinese developer community can start to send pull requests in a more compliant way (to avoid future conflicts when new tooling improvements come from Microsoft).

**Comment by nokura** [comment]
Hello, thank you for your input.  Our team is working on a localized contributor guide. Hopefully it will be posted soon.

**Comment by nokura** [comment]
Hello @lextm 
Please refer to the standard contribution guideline for docs.microsoft.com at https://docs.microsoft.com/zh-cn/contribute/
