### ISSUE TITLE
Incomplete translation

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs.zh-cn#201]
see https://github.com/dotnet/docs.zh-cn/blame/live/docs/standard/generics/index.md#L84.

Note this issue exists almost in all other repos. But I didn't see any thing unusual in en-us repo.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0fc82239-30f3-14d2-ed23-5c0b66bd370e
* Version Independent ID: 26fccd46-c489-1a05-2da2-dda3a8e5fac8
* Content: [.NET 中的泛型](https://docs.microsoft.com/zh-cn/dotnet/standard/generics/)
* Content Source: [docs/standard/generics/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/generics/index.md)
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by LisandroSu** [comment]
Hello, @imba-tjd 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @imba-tjd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://github.com/dotnet/docs.zh-cn/blame/live/docs/standard/generics/index.md#L84.  (all locales)

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
