### ISSUE TITLE
翻译勘误

### ISSUE THREAD

**Issue by guyigenius** [dotnet/docs.zh-cn#213]
在[静态成员](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members#static-members)一节中：“静态成员只有一个副本存在（与创建的类的实例数有关）。”此句翻译有误，[原文](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members#static-members)是“Only one copy of a static member exists, regardless of how many instances of the class are created.”，翻译成了完全相反的意思，应当将“有关”改为“无关”。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7f20db0d-ef5c-d8e7-2267-0f409c499e0f
* Version Independent ID: de2dac73-e810-dd42-f518-e50926b3747f
* Content: [静态类和静态类成员（C# 编程指南）](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/classes-and-structs/static-classes-and-static-class-members.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
你好，@guyigenius
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team
