### ISSUE TITLE
about https server development

### ISSUE THREAD

**Issue by dldavid110** [dotnet/docs.zh-cn#214]
[在此处输入反馈]
Could you please create a demo to show how can I create a HTTPS server and client? I don't know how can I validate the ssl certificate by use C# language both at  Server part  and at client part. Thank you very much!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 467b61ab-04cc-2a5d-5be8-2fd37034c7fa
* Version Independent ID: 0bf63c68-cad3-3e9e-a5a9-453d40f1dd6d
* Content: [SslStream Class (System.Net.Security)](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.security.sslstream?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.Net.Security/SslStream.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Net.Security/SslStream.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hello, @dldavid110 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
