### ISSUE TITLE
Logical Error?

### ISSUE THREAD

**Issue by yiwangwenrou** [dotnet/docs.zh-cn#219]
DBBool TRUE = DBBool.True,NULL = DBBool.Null;    if(NULL && TRUE)  与 if(!(NULL && TRUE)   都为逻辑true

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f818b111-bdeb-96a1-721a-1be183519f6d
* Version Independent ID: e98c5f3f-24d8-ae0e-d4b8-5607ce40f6b9
* Content: [false 运算符（C# 参考）](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/false-operator#see-also)
* Content Source: [docs/csharp/language-reference/keywords/false-operator.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/false-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
I actually got `DBBool.Null`, both of them.
![default](https://user-images.githubusercontent.com/24759802/47075706-a5196180-d22f-11e8-981e-dde9ab6e266b.png)

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #8444](https://github.com/dotnet/docs/issues/8444) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
你好，@yiwangwenrou

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/8444。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
