### ISSUE TITLE
a named namespace use global namespace

### ISSUE THREAD

**Issue by xuxuedong** [dotnet/docs.zh-cn#228]
Is a named namespace use global namespace need to use "using global" directive?
or
Is a nested namespace use his father namespace need to use "using father" directive?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f74806f9-ada9-ab38-bc26-d54bfb789da7
* Version Independent ID: 0fa374d3-04b8-fd8a-65f4-cd69944e27bf
* Content: [命名空间关键字（C# 参考）](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/namespace)
* Content Source: [docs/csharp/language-reference/keywords/namespace.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/namespace.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Hello, @xuxuedong 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
