### ISSUE TITLE
translate error lead to mislead

### ISSUE THREAD

**Issue by xuxuedong** [dotnet/docs.zh-cn#230]
on the left tile, array should be translated "数组" instead of "阵列"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fc2fe8f7-b023-5aa7-52c2-b9c1c5c13ded
* Version Independent ID: 18c373d4-02f9-4cc6-656d-9cf4d11f6498
* Content: [C# 编程指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/)
* Content Source: [docs/csharp/programming-guide/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Hello, @xuxuedong 
 
Thank you for your feedback.
 
We will continue to work on this issue on PR https://github.com/dotnet/docs.zh-cn/pull/231 which includes this fix for many other files.

Kind regards,
Microsoft DOCS International Team
