### ISSUE TITLE
translation misleading

### ISSUE THREAD

**Issue by xuxuedong** [dotnet/docs.zh-cn#260]
原文英文：”There is extensive support for these procedures in Visual Studio.“
原文翻译：“在 Visual Studio 中没有对这些过程的扩展支持。”

我的翻译：”在 Visual Studio 中有对这些过程的大量扩展支持“

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 785592e0-9e79-8b25-8288-dd15e6516c8a
* Version Independent ID: fe29ea5c-2b95-f6e7-d52b-cc042e5da243
* Content: [如何： 从命令行创建 Windows 窗体应用程序](https://docs.microsoft.com/zh-cn/dotnet/framework/winforms/how-to-create-a-windows-forms-application-from-the-command-line)
* Content Source: [docs/framework/winforms/how-to-create-a-windows-forms-application-from-the-command-line.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/winforms/how-to-create-a-windows-forms-application-from-the-command-line.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Hello, @xuxuedong 

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Also, for this specific suggestion, you may want to create a Pull Request to fix the translation.

![imagen](https://user-images.githubusercontent.com/26746247/49038959-2f44d600-f19d-11e8-9969-c2162f11186e.png)

Kind regards,
Microsoft DOCS International Team
