### ISSUE TITLE
中文翻译错误

### ISSUE THREAD

**Issue by htlsmilework** [dotnet/docs.zh-cn#272]
该页面里的“Visual Studio 15.7 and later”翻译成了“Visual Studio 15.7及更早版本”，应该翻译为“Visual Studio 15.7及更高版本”。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 50511188-600e-18f6-6d92-c93b135d3db6
* Version Independent ID: 559262e6-f27b-e581-255f-0967b006a922
* Content: [使用 Visual Studio 部署 .NET Core 应用](https://docs.microsoft.com/zh-cn/dotnet/core/deploying/deploy-with-vs?tabs=vs156)
* Content Source: [docs/core/deploying/deploy-with-vs.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/deploying/deploy-with-vs.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
你好，@htlsmilework
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team
