### ISSUE TITLE
 Unable to load the service

### ISSUE THREAD

**Issue by 15302202842** [dotnet/docs.zh-cn#273]
run: docker build -t aspnetapp .
occur the error:
PS E:\dotnet-docker\samples\aspnetapp&gt; docker build -t aspnetapp .
Sending build context to Docker daemon  4.754MB
Step 1/12 : FROM microsoft/dotnet:2.1-sdk AS build
 ---&gt; f79b064f8ac8
Step 2/12 : WORKDIR /app
 ---&gt; Using cache
 ---&gt; 3e41e0be1664
Step 3/12 : COPY *.sln .
 ---&gt; Using cache
 ---&gt; bb5e09b27bd0
Step 4/12 : COPY aspnetapp/*.csproj ./aspnetapp/
 ---&gt; Using cache
 ---&gt; b13a09b00a0d
Step 5/12 : RUN dotnet restore
 ---&gt; Running in 1e229b6ade5f
  Restoring packages for C:\app\aspnetapp\aspnetapp.csproj...
C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\app\aspnetapp.sln]
C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error :   No such host is known [C:\app\aspnetapp.sln]
The command 'cmd /S /C dotnet restore' returned a non-zero code: 1

how to solove it?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9731aae1-505b-abb1-0d4b-d6a83ec735e1
* Version Independent ID: 760790d5-0e81-ea6c-19ea-f226d08ddf1f
* Content: [生成 .NET Core Docker 映像](https://docs.microsoft.com/zh-cn/dotnet/core/docker/building-net-docker-images?view=aspnetcore-2.1)
* Content Source: [docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/docker/building-net-docker-images.md)
* Product: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Hello, @15302202842 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
