### ISSUE TITLE
\s	与任何空白字符匹配。	\w\s	“ID A1.3”中的“D”。

### ISSUE THREAD

**Issue by Epsilon2019** [dotnet/docs.zh-cn#279]
这个页面的错误太多了，微软不应该是很权威的吗？才看了一点点，就很多错误，随便举几个例子。
1、\s	与任何空白字符匹配。	\w\s	“ID A1.3”中的“D”。
正确的匹配应该是"D "吧。
2、\A	匹配必须出现在字符串的开头。	\A\d{3}	“901-333-”中的“901-”
正确的匹配应该是"901"吧。
还有很多，就不举例了，烦请快速更正一下，谢谢！！！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [正则表达式语言 - 快速参考](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/regular-expression-language-quick-reference)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by imba-tjd** [comment]
这是翻译的问题，你可以看英文版，没有你说的这两个问题。如果英文版也有问题可以提出来。

**Comment by CeciAc** [comment]
你好，@Epsilon2019
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Epsilon2019

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/regular-expression-language-quick-reference。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @NextTurn 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @NextTurn 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/regular-expression-language-quick-reference

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
