### ISSUE TITLE
页面显示issue

### ISSUE THREAD

**Issue by Vyner** [dotnet/docs.zh-cn#280]
相加运算符一栏下显示     x：y：减法。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# 运算符](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/index#feedback)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
你好，@Vyner
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team
