### ISSUE TITLE
前后指定终结点不一致

### ISSUE THREAD

**Issue by laohur** [dotnet/docs.zh-cn#295]
"此示例将配置客户端用于访问位于以下地址的服务的终结点： http://localhost:8000/ServiceModelSamples/Service/CalculatorService" 建议与前文保持一致,改为"http://localhost:8000/GettingStarted/CalculatorService"

[更改如下]
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup>
    
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0,Profile=Client" />
  </startup>
  <system.serviceModel>
    <bindings>
      
      <wsHttpBinding>
        <binding name="WSHttpBinding_ICalculator" />
      </wsHttpBinding>
    </bindings>
    <client>
      
      <endpoint address="http://localhost:8000/GettingStarted/CalculatorService"
          binding="wsHttpBinding" bindingConfiguration="WSHttpBinding_ICalculator"
          contract="ServiceReference1.ICalculator" name="WSHttpBinding_ICalculator">
        <identity>
          <userPrincipalName value="migree@redmond.corp.microsoft.com" />
        </identity>
      </endpoint>
    </client>
  </system.serviceModel>
</configuration>

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 05c2edb7-168e-ea7c-3f5a-3fdc226c68a3
* Version Independent ID: b8b5bd7f-14cd-ecd5-ecc3-a73bfcc28a99
* Content: [如何：配置基本 Windows Communication Foundation 客户端](https://docs.microsoft.com/zh-cn/dotnet/framework/wcf/how-to-configure-a-basic-wcf-client)
* Content Source: [docs/framework/wcf/how-to-configure-a-basic-wcf-client.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wcf/how-to-configure-a-basic-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by laohur** [comment]
另,最好更改配置环境为"    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0,Profile=Client" />
"

**Comment by imba-tjd** [comment]
Since you have created a issue in https://github.com/dotnet/docs/issues/9654, you should close this one.

**Comment by CeciAc** [comment]
你好，@laohur
非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 #[https://github.com/dotnet/docs/issues/9654]。因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
