### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by OkShen** [dotnet/docs.zh-cn#298]
Lambda 表达式和元祖
应为
Lambda 表达式和元组

Func&lt;(int n1, int n2, int n3, int n4, int n5), (int, int, int, int, int)&gt; doubleThem = (n) =&gt; (n.n1 * 2, n2 * 2, n.n3 * 2, n.n4 * 2, n.n5 * 2);
应为
Func&lt;(int n1, int n2, int n3, int n4, int n5), (int, int, int, int, int)&gt; doubleThem = (n) =&gt; (n.n1 * 2, n.n2 * 2, n.n3 * 2, n.n4 * 2, n.n5 * 2);

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 12c8b202-5b65-9d30-d57e-dd060a507b9a
* Version Independent ID: 92cfc461-56ed-c046-bb03-cc5e46ebf5ba
* Content: [Lambda 表达式](https://docs.microsoft.com/zh-cn/dotnet/csharp/lambda-expressions)
* Content Source: [docs/csharp/lambda-expressions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/lambda-expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
你好，@OkShen
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@OkShen

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 
[https://github.com/dotnet/samples/pull/537]
[https://github.com/dotnet/docs.zh-cn/pull/299]

因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
