### ISSUE TITLE
TypeInfo不存在

### ISSUE THREAD

**Issue by bingoabs** [dotnet/docs.zh-cn#307]
环境：
Mac Darwin osx.10.12-x64
.NET Core SDK 2.2.101
.NET Core runtimes 2.2.0
问题：
The type or namespace name 'TypeInfo' could not be found (are you missing a using directive or an assembly reference?) [/Users/bingokarl/project/dot_nets/attributes/attributes.csproj]

这是否需要.Net Core版本为3.0才可运行？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b0949aaa-0396-f42e-9228-36f63917fcbb
* Version Independent ID: 0ff9f93b-99f7-1d35-2521-1b9583f799be
* Content: [属性 - C#](https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/attributes)
* Content Source: [docs/csharp/tutorials/attributes.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tutorials/attributes.md)
* Product: **dotnet-csharp**
* GitHub Login: @mgroves
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
Could you provide the code you are testing?

**Comment by CeciAc** [comment]
你好，@bingoabs

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by bingoabs** [comment]
@CeciAc  Sorry, I do not know the comment will publish on the `doc issue`, so I did't paste the doc content. Anyway I have fix the error. Thanks again.

**Comment by bingoabs** [comment]
> Could you provide the code you are testing?
> Add `using System.Reflection;` in the front of your code.

@imba-tjd  Thanks, I do not try this way. 

I came cross the issue when I write `TypeInfo widgetType = typeof(Widget).getType()`.

After some search, I find change to the `Type widgetType = typeof(Widget)` will fix this problem. But I dot't know the difference between the two expressions.
