### ISSUE TITLE
元数据属性名误翻译(属性名应保留英文)

### ISSUE THREAD

**Issue by frankli0324** [dotnet/docs.zh-cn#311]
文档中的元数据属性："标题", "作者", "说明"不应翻译为中文。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [.NET Core 的 csproj 格式的新增内容](https://docs.microsoft.com/zh-cn/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by LisandroSu** [comment]
你好，@frankli0324
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by frankli0324** [comment]
已提交pr
