### ISSUE TITLE
FilterPlugin didn't work on strokes.

### ISSUE THREAD

**Issue by Thxzzzzz** [dotnet/docs.zh-cn#318]
When DynamicRenderer ink vanished,the static ink create by strokes still out of the area。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5bbdae12-e7bc-c6ff-f62e-2c002e024f0d
* Version Independent ID: 53a2e4e1-f9cc-d2aa-30b2-60d1c9cc7a39
* Content: [截获触笔输入](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/advanced/intercepting-input-from-the-stylus#AddingYourPluginToAnInkCanvas)
* Content Source: [docs/framework/wpf/advanced/intercepting-input-from-the-stylus.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/advanced/intercepting-input-from-the-stylus.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@Thxzzzzz
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
