### ISSUE TITLE
Cacography

### ISSUE THREAD

**Issue by lienonegithub** [dotnet/docs.zh-cn#321]
//
            // Create a TileBrush with FlipY tiling.
            // The brush's content is flipped vertically as it is
            // tiled in this example
            //
            DrawingBrush tileBrushWithFlipYTiling = new DrawingBrush();
            tileBrushWithFlipYTiling.Drawing = triangleDrawing;
            tileBrushWithFlipYTiling.TileMode = TileMode.FlipX;

            // Specify the brush's Viewport.
            tileBrushWithFlipYTiling.Viewport = new Rect(0, 0, 0.5, 0.5);

            // Create a rectangle and paint it with the DrawingBrush.
            Rectangle flipYTilingExampleRectangle = createExampleRectangle();
            flipYTilingExampleRectangle.Fill = tileBrushWithFlipYTiling;
            mainPanel.Children.Add(createExampleHeader("FlipY"));
            mainPanel.Children.Add(flipYTilingExampleRectangle);

tileBrushWithFlipYTiling.TileMode = TileMode.FlipX; 
-&gt; TileMode.FlipY

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bd8c50dc-70d0-3d58-5b15-f6a063484cf9
* Version Independent ID: ddfefb93-bcc3-4233-a367-bb33c357c0db
* Content: [如何：使用 TileBrush 创建不同的平铺模式](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/graphics-multimedia/how-to-create-different-tile-patterns-with-a-tilebrush#feedback)
* Content Source: [docs/framework/wpf/graphics-multimedia/how-to-create-different-tile-patterns-with-a-tilebrush.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/graphics-multimedia/how-to-create-different-tile-patterns-with-a-tilebrush.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hello, @lienonegithub 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review PR https://github.com/dotnet/samples/pull/565 . For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
