### ISSUE TITLE
缺少标点

### ISSUE THREAD

**Issue by Jisu-Woniu** [dotnet/docs.zh-cn#325]
在short和ushort之间应添加`、`

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 86308a57-1418-cf16-94f7-d840d56f6dda
* Version Independent ID: cdb096f4-7498-2db7-ad2d-cd7c794b0bee
* Content: [隐式数值转换表 - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/implicit-numeric-conversions-table)
* Content Source: [docs/csharp/language-reference/keywords/implicit-numeric-conversions-table.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/implicit-numeric-conversions-table.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
你好，@Jisu-Woniu

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/implicit-numeric-conversions-table。  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
