### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by CSharperMantle** [dotnet/docs.zh-cn#334]
# Translation issue
We found that in the Chinese version of this page of [Tutorial: Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/sentiment-analysis) at `https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/sentiment-analysis`, there is a translation issue. The sentence
>Training data: website comments can be toxic (1) or not toxic (0) (sentiment).

should be translated like
>定型数据：网站评论可以是负面 (1) 或正面 (0)（情绪）。

in Chinese. 
However, the website has gone wrong a bit. The translation on it is
>定型数据：网站评论可以是负面 (0) 或正面 (1)（情绪）。

For better reading experiences in Chinese, We set up this issue. We look forward to hearing from you.

**Comment by CeciAc** [comment]
Hello, @CSharperMantle 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @CSharperMantle 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/sentiment-analysis

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
