### ISSUE TITLE
CSS1558

### ISSUE THREAD

**Issue by MIAIONE** [dotnet/docs.zh-cn#335]
无法解决呀

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2f47b50a-3c77-4363-3e25-c4bf201e3d4a
* Version Independent ID: a04a3468-49de-a2a5-019c-b3634fd78b63
* Content: [编译器错误 CS1558](https://docs.microsoft.com/zh-cn/dotnet/csharp/misc/cs1558)
* Content Source: [docs/csharp/misc/cs1558.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/misc/cs1558.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
你好，@MIAIONE
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@MIAIONE
我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@MIAIONE
再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。
顺祝商祺！
Microsoft DOCS 国际团队
