### ISSUE TITLE
更改客户姓名和客户ID后，怎么都提交不了，怎么办啊

### ISSUE THREAD

**Issue by tking222** [dotnet/docs.zh-cn#344]
未处理System.ArgumentOutOfRangeException
  HResult=-2146233086
  Message=指定的参数已超出有效值的范围。
参数名: index
  Source=System.Data.Linq
  ParamName=index
  StackTrace:
       在 System.Data.Linq.EntitySet`1.get_Item(Int32 index)
       在 LinqDataManipulationApp.Program.Main(String[] args) 位置 e:\Users\zz\Documents\Visual Studio 2013\Projects\LinqDataManipulationApp\LinqDataManipulationApp\Program.cs:行号 39
       在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       在 System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1d26089c-984a-4e94-8bcb-819ed330eee5
* Version Independent ID: aaa90971-a4a7-bcc2-bcc4-63c4716cd3cb
* Content: [演练：操作数据 (C#)](https://docs.microsoft.com/zh-cn/dotnet/framework/data/adonet/sql/linq/walkthrough-manipulating-data-csharp#feedback)
* Content Source: [docs/framework/data/adonet/sql/linq/walkthrough-manipulating-data-csharp.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/data/adonet/sql/linq/walkthrough-manipulating-data-csharp.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by CeciAc** [comment]
你好，@tking222
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
