### ISSUE TITLE
a

### ISSUE THREAD

**Issue by FreeXiaoSuYu** [dotnet/docs.zh-cn#349]
adasdsafs

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core 应用程序部署](https://docs.microsoft.com/zh-cn/dotnet/core/deploying/index#feedback)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Empty feedback
