### ISSUE TITLE
vs studio 对 C#7.0中is 关键字的编译支持不完美！

### ISSUE THREAD

**Issue by 15168440402** [dotnet/docs.zh-cn#350]
代码:
object b=1;
_=b ?? throw new Exception("");
_=b is int  a;
编译运行正常，代码调试显示a的值为1；
代码添加一句：
 Console.WriteLine(a);
此时vs studio显示错误“使用了未赋值的局部变量a”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dc229b53-a548-4ef8-86b9-58670a81344a
* Version Independent ID: aeb15230-e1cc-df50-7edb-fb50164e13be
* Content: [C# 7.0 中的新增功能 - C# 指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/whats-new/csharp-7#feedback)
* Content Source: [docs/csharp/whats-new/csharp-7.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/whats-new/csharp-7.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
你好，@15168440402
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
