### ISSUE TITLE
翻译勘误

### ISSUE THREAD

**Issue by Lynettejin90** [dotnet/docs.zh-cn#352]
[在此处输入反馈]
由于在运行时 AOT 工具链不编译=》由于在运行时 AOT 工具并不编译

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: aa071095-4eb6-20c1-ca26-f34da6fcbdf8
* Version Independent ID: 2b2efd49-b0c8-9a13-525a-d04c802d2bef
* Content: [.NET 术语表](https://docs.microsoft.com/zh-cn/dotnet/standard/glossary)
* Content Source: [docs/standard/glossary.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/glossary.md)
* Product: **dotnet**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
你好，@Lynettejin90
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Lynettejin90

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/standard/glossary

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
