### ISSUE TITLE
违反了类型“V2”的约束什么意思

### ISSUE THREAD

**Issue by tking222** [dotnet/docs.zh-cn#356]
未处理System.ArgumentException
  HResult=-2147024809
  Message=“System.Data.Linq.Mapping.PropertyAccessor+Accessor`3[T,V,V2]”上的 GenericArguments[2]“System.String”违反了类型“V2”的约束。
  Source=mscorlib
  StackTrace:
       在 System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
       在 System.RuntimeType.MakeGenericType(Type[] instantiation)
       在 System.Data.Linq.Mapping.PropertyAccessor.Create(Type objectType, PropertyInfo pi, MetaAccessor storageAccessor)
       在 System.Data.Linq.Mapping.AttributedMetaDataMember.MakeMemberAccessor(Type accessorType, MemberInfo mi, MetaAccessor storage)
       在 System.Data.Linq.Mapping.AttributedMetaDataMember.InitAccessors()
       在 System.Data.Linq.Mapping.AttributedMetaDataMember.get_StorageAccessor()
       在 System.Data.Linq.ChangeTracker.StandardChangeTracker.StandardTrackedObject.CreateDataCopy(Object instance)
       在 System.Data.Linq.ChangeTracker.StandardChangeTracker.OnPropertyChanging(Object sender, PropertyChangingEventArgs args)
       在 System.Data.Linq.ChangeTracker.StandardChangeTracker.Attach(Object obj)
       在 System.Data.Linq.ChangeTracker.StandardChangeTracker.FastTrack(Object obj)
       在 System.Data.Linq.CommonDataServices.OnEntityMaterialized(MetaType type, Object instance)
       在 System.Data.Linq.SqlClient.ObjectReaderCompiler.ObjectReaderBase`1.SendEntityMaterialized(Int32 iMetaType, Object instance)
       在 Read_Order(ObjectMaterializer`1 )
       在 System.Data.Linq.SqlClient.ObjectReaderCompiler.ObjectReader`2.MoveNext()
       在 System.Data.Linq.EntitySet`1.Load()
       在 System.Data.Linq.EntitySet`1.get_Count()
       在 LinqConsoleApp.Program.Main(String[] args) 位置 e:\Users\vking\Documents\Visual Studio 2013\Projects\LinqConsoleApp\LinqConsoleApp\Program.cs:行号 112
       在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       在 System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.TypeLoadException
       HResult=-2146233054
       Message=“System.Data.Linq.Mapping.PropertyAccessor+Accessor`3[T,V,V2]”上的 GenericArguments[2] (“System.String”)与类型参数“V2”的约束冲突。
       Source=mscorlib
       TypeName=""
       StackTrace:
            在 System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
            在 System.RuntimeTypeHandle.Instantiate(Type[] inst)
            在 System.RuntimeType.MakeGenericType(Type[] instantiation)
       InnerException: 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a4c6dd4b-d45d-4897-e013-3731a31abedd
* Version Independent ID: bb870d3d-2ec8-754c-c7b2-d9633a825964
* Content: [演练：跨关系查询 (C#)](https://docs.microsoft.com/zh-cn/dotnet/framework/data/adonet/sql/linq/walkthrough-querying-across-relationships-csharp#feedback)
* Content Source: [docs/framework/data/adonet/sql/linq/walkthrough-querying-across-relationships-csharp.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/data/adonet/sql/linq/walkthrough-querying-across-relationships-csharp.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by CeciAc** [comment]
你好，@tking222
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
