### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by JackJCSN** [dotnet/docs.zh-cn#358]
[在此处输入反馈]
原文：将编译未通过 Compiled 选项的规范绑定到正则表达式引擎的正则表达式模式。
正确翻译：将编译通过 Compiled 选项的规范绑定到正则表达式引擎的正则表达式模式。
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 14698b87-a995-290f-bdd7-9c2d6867704c
* Version Independent ID: f199cd3f-8dce-ad4e-9712-3545e35557e7
* Content: [.NET 中的正则表达式最佳做法](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/best-practices)
* Content Source: [docs/standard/base-types/best-practices.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/best-practices.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
你好，@JackJCSN

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/docs.zh-cn/pull/359
因此我们将关闭这一重复的问题。 

深深的祝福， 
Microsoft DOCS International Team
