### ISSUE TITLE
安装.NET Framework 3.5报0x800f0950

### ISSUE THREAD

**Issue by HiGson** [dotnet/docs.zh-cn#361]
win10 18343.1安装.NET Framework 3.5报0x800f0950,各种方法都试过了，总是失败

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [在 Windows 10、Windows 8.1 和 Windows 8 上安装 .NET Framework 3.5](https://docs.microsoft.com/zh-cn/dotnet/framework/install/dotnet-35-windows-10#feedback)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment]
你好，@HiGson
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
