### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by EraserKing** [dotnet/docs.zh-cn#373]
In zh-cn document: "可以使用以下包含 swith 表达式的方法将 Rainbow 值转换为其 RGB 值：", in which, "swith" should be corrected with "switch".

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [C# 8.0 中的新增功能 - C# 指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by EraserKing** [comment]
#374 fixes this typo

**Comment by CeciAc** [comment]
Hello, @EraserKing 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #374 

Kind regards,
Microsoft DOCS International Team

**Comment by EraserKing** [comment]
You're welcome. #374 is my PR to fix this typo ;)
