### ISSUE TITLE
May i get the named blocks in details?

### ISSUE THREAD

**Issue by xp44mm** [dotnet/docs.zh-cn#375]
how to use the named blocks, and what characters do the name represent?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a1958bf6-a17d-1256-d659-31066aa02604
* Version Independent ID: 95abea42-fa7f-3feb-ae38-049719ab938f
* Content: [.NET 正则表达式中的字符类](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/character-classes-in-regular-expressions#SupportedNamedBlocks)
* Content Source: [docs/standard/base-types/character-classes-in-regular-expressions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/character-classes-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by imba-tjd** [comment]
your two questions has already been covered in the page you visit.

**Comment by CeciAc** [comment]
Hello, @xp44mm

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
