### ISSUE TITLE
transfer learning 翻译

### ISSUE THREAD

**Issue by redcican** [dotnet/docs.zh-cn#380]
transfer learning 翻译成迁移学习是否更好?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [.NET 机器学习教程 - ML.NET](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/machine-learning/tutorials/index.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
你好，@redcican
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@redcican

感谢你提交的语言方面的反馈。  

遗憾的是，我们语言团队评审你的反馈后，认为它不完全符合我们的接受条件，因为 [“迁移”可能会让读者将"transfer"和"migrate"混淆。] 

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福， 
Microsoft DOCS International Team
