### ISSUE TITLE
中文是否有pdf

### ISSUE THREAD

**Issue by L261173157** [dotnet/docs.zh-cn#383]
中文是否有pdf

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: be16c8cd-c7df-baf4-f649-64250f8e3fc9
* Version Independent ID: 0cead786-5529-c4a0-31cc-047a3affe4b2
* Content: [Windows Presentation Foundation](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/#feedback)
* Content Source: [docs/framework/wpf/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/index.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment]
dup of https://github.com/dotnet/docs.zh-cn/issues/58

**Comment by CeciAc** [comment]
你好，@L261173157

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 #58  。因此我们将关闭这一重复的问题。 

深深的祝福， 
Microsoft DOCS International Team
