### ISSUE TITLE
The training data is in Chinese and the results are as follows. There are very few items with the same tag value.Does this mean that the model is too bad to be used？Thank you for answering。

### ISSUE THREAD

**Issue by lfzx** [dotnet/docs.zh-cn#385]
*       Metrics for Multi-class Classification model - Test Data
*------------------------------------------------------------------------------------------------------------
*       MicroAccuracy:    0.6
*       MacroAccuracy:    0.6
*       LogLoss:          3.225
*       LogLossReduction: -100.398
*************************************************************************************************************

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 77fc5686-2288-d607-8136-3146ed02dbf6
* Version Independent ID: 8a16b9e9-b5cb-a55e-2135-191bc62c1656
* Content: [在 GitHub 问题多类分类方案中使用 ML.NET - ML.NET](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/github-issue-classification#results)
* Content Source: [docs/machine-learning/tutorials/github-issue-classification.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/machine-learning/tutorials/github-issue-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by lfzx** [comment]
拥有同一标签值得项很少。

**Comment by CeciAc** [comment]
Hello, @lfzx

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
