### ISSUE TITLE
404

### ISSUE THREAD

**Issue by mcxtlong** [dotnet/docs.zh-cn#396]
[在此处输入反馈]
http://www.contoso.com/default.html
404 not found

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6d0d3c05-6a37-ccb6-d897-a4c35beb2597
* Version Independent ID: a826593c-e1e0-2caa-c764-3e3f63322892
* Content: [如何：使用 WebRequest 类请求数据](https://docs.microsoft.com/zh-cn/dotnet/framework/network-programming/how-to-request-data-using-the-webrequest-class)
* Content Source: [docs/framework/network-programming/how-to-request-data-using-the-webrequest-class.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/network-programming/how-to-request-data-using-the-webrequest-class.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #12641](https://github.com/dotnet/docs/issues/12641) via [**ZenHub**](https://www.zenhub.com/)
