### ISSUE TITLE
具体类可以继承开放式泛型构造类型

### ISSUE THREAD

**Issue by llxxs** [dotnet/docs.zh-cn#398]
泛型类的内部具体类可以继承开放式构造类型。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c0dc56d1-11c0-6d67-4b1f-097579060aed
* Version Independent ID: 425af41b-cf95-94f8-b729-091a9d6bc610
* Content: [泛型类 - C# 编程指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/generics/generic-classes#feedback)
* Content Source: [docs/csharp/programming-guide/generics/generic-classes.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/generics/generic-classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
你好，@llxxs
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
