### ISSUE TITLE
翻译有问题

### ISSUE THREAD

**Issue by letianccc** [dotnet/docs.zh-cn#401]
“还可以将返回多个派生类型（协变）的方法分配给委托，或者将所接受参数的派生类型（逆变）数目比委托类型指定的数目少的方法分配给委托。 这包括泛型委托和非泛型委托。”
more和less指的是派生程度，而不是方法数量。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0e34cc1a-4658-d7ce-741d-8d81c1701682
* Version Independent ID: 1fcbc3ff-e3f1-e0a7-7373-16ae150a0de8
* Content: [委托中的变体 (C#)](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
你好，@
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@letianccc

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/concepts/covariance-contravariance/variance-in-delegates#feedback

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
