### ISSUE TITLE
翻译勘误

### ISSUE THREAD

**Issue by Nosta1gia** [dotnet/docs.zh-cn#402]
Delegate types are sealed.
原译：委托类型是封装的。
更正：委托类型是密封的。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8b5dba5b-eabc-8202-2854-6b1f4a7f971a
* Version Independent ID: 8b2e46f0-6d12-6ce9-944d-b883dcbe0808
* Content: [使用委托 - C# 编程指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/delegates/using-delegates#feedback)
* Content Source: [docs/csharp/programming-guide/delegates/using-delegates.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/delegates/using-delegates.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
你好，@Nosta1gia
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Nosta1gia

感谢你提交的语言方面的反馈。  

遗憾的是，我们语言团队评审你的反馈后，认为它不完全符合我们的接受条件，因为 [“封装”是全局使用的术语，需要保持一致。] 

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福， 
Microsoft DOCS International Team
