### ISSUE TITLE
64位Win10系统安装Net framework3.5

### ISSUE THREAD

**Issue by dyd1947** [dotnet/docs.zh-cn#406]
我有个机械制图软件，旧的简单，新的我不会用。在Win10系统里安装，以前自动安装过Net framework3.5，没有顺利运行。这次它还是说灾难性故障，现在安装一部分，安装不上卸载不了。现在想法安装Net 3.5吧。

64位Win10系统安装.Net framework3.5：
在“管理员:命令提示符（或管理员: Windows PowerShell）”窗口中输入以下命令：
dism.exe /online /enable-feature /featurename:netfx3 /Source:V:\sources\sxs回车，等待部署完毕，进度100%，提示“操作成功完成”。
问题是：输入命令后，按回车点确认都一样，往下不运行了，没进度。
https://blog.csdn.net/liangzhao_jay/article/details/79731414

直接在线安装 
直接点击【控制面板】-【程序】【程序和功能】-【打开或关闭windows功能】，找到NET3.5，我本机是在最上面，将两个子选项都选上，确定后会自动联网下载完成安装。
问题是：从【打开或关闭windows功能】，往下不运行了，找不到NET3.5
https://blog.csdn.net/ayang1986/article/details/82467708

有人提出以下原因，说出来供你参考：
1、这么棘手的问题估计是一些系统文件出问题了，所以第一步就是修复系统：按“Windows+X”点击“命令提示符管理员”，输入“SFC /scannow”回车（该操作可能需要一段时间，please wait a minute...），再输入“dism /online /cleanup-image /restorehealth”回车。然后，估计还得等一会儿。
2、导致你安装不上的原因还有可能是你的注册表里残留的无用注册表引起的（比如删除过的用户信息注册表、过期软件注册表....），可以去百度上download一个注册表清理工具，很快就能清理完（即便不是这个原因导致的，清理一下注册表也没什么坏处）。
https://blog.csdn.net/zang141588761/article/details/52177290

我无法安装下载NET Framework 3.5，按上面这人说的操作行吗，请帮助。给我软件链接也可以。
丁衍德d4728@hotmail.com  2019/6/25/

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [在 Windows 10、Windows 8.1 和 Windows 8 上安装 .NET Framework 3.5](https://docs.microsoft.com/zh-cn/dotnet/framework/install/dotnet-35-windows-10#feedback)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by imba-tjd** [comment]
这种问题请左转百度贴吧

**Comment by dyd1947** [comment]
谭九鼎先生：

您好。

我说的【64位Win10系统安装Net framework3.5 (#406)】一事，其他人是否也存在。我有个机械制图软件，旧的简单，新的我不会用，所以我不得不安装Net 3.5。

从下面我的叙述，你知道它困扰我不是一天了；我探讨过解决办法，没有成功。第一位和第二位的解决方法，我试过没成功。

第三位的说法，就有可能了：

①系统文件出问题了或者改变了，需要修复系统。

②我的注册表里，有了残留无用注册，在上次的Win10安装这软件时就存在；不记得怎么搞的了，上次没有认真安装Net 3.5，勉强能用，但不顺利；这次重装Win10重装制图软件，现在装不上也卸载不了，我想清理一下注册表。

牵扯到系统文件的改动，和清理注册表所用软件，希望有Win10系统的编程人员认可；我觉的这样办，更可靠，成功的几率更高些。

礼                 丁衍德d4728@hotmail.com  2019/6/25/


________________________________
发件人: 谭九鼎 <notifications@github.com>
发送时间: 2019年6月24日 2:41
收件人: dotnet/docs.zh-cn
抄送: dyd1947; Author
主题: Re: [dotnet/docs.zh-cn] 64位Win10系统安装Net framework3.5 (#406)


这种问题请左转百度贴吧

―

**Comment by CeciAc** [comment]
你好，@dyd1947
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by dyd1947** [comment]
i am

**Comment by dyd1947** [comment]
Microsoft DOCS International Team

您好。

根据你的建议，我想使用 DOCS 页面底部的“提供产品反馈”按钮，记录我的产品反馈，可惜我没找到“提供产品反馈”按钮。请告知我寻找的位置或者链接。

给我NET Framework 3.5的链接，我试着下载安装，也可以。

礼                 丁衍德d4728@hotmail.com  2019/6/25


________________________________
发件人: Cecilia Acevedo <notifications@github.com>
发送时间: 2019年6月24日 14:24
收件人: dotnet/docs.zh-cn
抄送: dyd1947; Mention
主题: Re: [dotnet/docs.zh-cn] 64位Win10系统安装Net framework3.5 (#406)


你好，@dyd1947<https://github.com/dyd1947>
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。

非常感谢你对我们的文章作出的贡献。

深深的祝福，
Microsoft DOCS International Team

―

**Comment by CeciAc** [comment]
![imagen](https://user-images.githubusercontent.com/26746247/60100239-af311f80-972f-11e9-8d9a-22418535208e.png)

https://developercommunity.visualstudio.com/spaces/61/index.html
