### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by wwwhyme** [dotnet/docs.zh-cn#408]
第一个框代码和第二个代码相同，但产生不同的运行输出结果
Person person2 = person1;
Person p2 = p1;

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 433a56c8-1c93-32fb-eb1d-8395a9760c65
* Version Independent ID: e3f35410-f243-4309-1436-89ade7a34d19
* Content: [对象 - C# 编程指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/objects#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/objects.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/classes-and-structs/objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
请好好看文章

```
public class Person
```

```
public struct Person
```

**Comment by wwwhyme** [comment]
对不起，我的锅
