### ISSUE TITLE
Task.Run don't use await.

### ISSUE THREAD

**Issue by tahen2** [dotnet/docs.zh-cn#409]
CPU 绑定示例：为游戏执行计算这个示例中，Task.Run函数前不能加await，如果加了就报错，去掉就可以了。
in the game's programe,Task.Run function don't use await.if you use ,the program will give a debug.
++++++++

calculateButton.Clicked += async (o, e) =&gt;
{
    // This line will yield control to the UI while CalculateDamageDone()
    // performs its work.  The UI thread is free to perform other work.
    var damageResult = Task.Run(() =&gt; CalculateDamageDone());
    DisplayDamage(damageResult);
};

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 07ed82a3-99c1-0893-4e81-d095b4757ecc
* Version Independent ID: 3765200b-43e5-441c-b290-709c34dd2f6d
* Content: [异步编程 - C#](https://docs.microsoft.com/zh-cn/dotnet/csharp/async#feedback)
* Content Source: [docs/csharp/async.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/async.md)
* Product: **dotnet-csharp**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by tahen2** [comment]
已经解决了。例题是没有问题的。方法必须有返回值。

**Comment by CeciAc** [comment]
你好，@tahen2

非常感谢你提供反馈。很高兴我们的文档满足你的期望。 
欢迎提供宝贵的反馈，以便我们继续改进体验。 


深深的祝福， 
Microsoft DOCS International Team
