### ISSUE TITLE
internal示例成功调用的例子是怎么样的

### ISSUE THREAD

**Issue by gallop1** [dotnet/docs.zh-cn#411]
如题，请列举一个正常调用的例子。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ac43c546-b79a-a4cb-6b59-7037334b83e0
* Version Independent ID: 4926fa62-f791-dc1a-7c09-7b268180d20e
* Content: [internal - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/internal)
* Content Source: [docs/csharp/language-reference/keywords/internal.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/internal.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #13249](https://github.com/dotnet/docs/issues/13249) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@gallop1
非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/13249

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
