### ISSUE TITLE
推荐影片中评估模型的代码有一段没显示出来

### ISSUE THREAD

**Issue by ChungYork** [dotnet/docs.zh-cn#416]
原文：
将以下代码添加到 EvaluateModel()，转换 Test 数据：[!code-csharpTransform]

[!code-csharpTransform]这里应该是
Console.WriteLine("=============== Evaluating the model ===============");
var prediction = model.Transform(testDataView);

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0888bc80-798f-ebdd-459a-7543be1efdad
* Version Independent ID: c24ded82-d56c-e8c7-fd6a-e39929227177
* Content: [教程：生成影片推荐系统 - 矩阵因子分解 - ML.NET](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/movie-recommendation#next-steps)
* Content Source: [docs/machine-learning/tutorials/movie-recommendation.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/machine-learning/tutorials/movie-recommendation.md)
* Product: **dotnet-ml**
* GitHub Login: @briacht
* Microsoft Alias: **johalex**

**Comment by imba-tjd** [comment]
https://github.com/dotnet/docs/pull/13446

**Comment by srvbpigh** [comment]
Hello, @ChungYork
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #13486](https://github.com/dotnet/docs/issues/13486) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@ChungYork
感谢你的反馈。 

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://github.com/dotnet/docs/issues/13486

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 

深深的祝福， 
Microsoft DOCS International Team
