### ISSUE TITLE
示例代码有错误（The sample code has errors）

### ISSUE THREAD

**Issue by xitangking** [dotnet/docs.zh-cn#417]
[Flags]
enum Days
{
    None = 0x0,
    Sunday = 0x1,
    Monday = 0x2,
    Tuesday = 0x4,
    Wednesday = 0x8,
    Thursday = 0x10,
    Friday = 0x20,
    Saturday = 0x40
}
class MyClass
{
    Days meetingDays = Days.Tuesday | Days.Thursday;
}

应该是 ：

    Thursday = 0x16,
    Friday = 0x32,
    Saturday = 0x64

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e72804b0-7d65-1585-67ea-863dc561124e
* Version Independent ID: 188ff9ab-de91-bf6a-d6a5-599389d2a76b
* Content: [枚举类型 - C# 编程指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/enumeration-types#feedback)
* Content Source: [docs/csharp/programming-guide/enumeration-types.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/enumeration-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @xitangking
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
0x是16进制的意思，0x10就是十进制的16。代码是没有问题的。

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #13508](https://github.com/dotnet/docs/issues/13508) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@xitangking

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/13508

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
