### ISSUE TITLE
左侧标题是Overrides，右侧标题是Overridable

### ISSUE THREAD

**Issue by programeralex** [dotnet/docs.zh-cn#418]
左侧标题是Overrides，右侧标题是Overridable

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a0d8080c-deeb-877d-66e7-8b5b9184cad6
* Version Independent ID: 020b95b0-6bab-35ac-ab30-6d561ecdf0f0
* Content: [Overridable (Visual Basic)](https://docs.microsoft.com/zh-cn/dotnet/visual-basic/language-reference/modifiers/overridable)
* Content Source: [docs/visual-basic/language-reference/modifiers/overridable.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/visual-basic/language-reference/modifiers/overridable.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @programeralex
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@programeralex

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/docs.zh-cn/pull/419 因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
