### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by xisimao** [dotnet/docs.zh-cn#428]
“工作站和服务器垃圾回收”小节最后"服务器垃圾回收既可以是非并发也可以是背景。"，背景应翻译成后台执行

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d8948cf5-0aec-308c-8046-965cc15763b2
* Version Independent ID: a30a0be5-b741-2a9c-e997-55d6d9960ca9
* Content: [垃圾回收的基本知识](https://docs.microsoft.com/zh-cn/dotnet/standard/garbage-collection/fundamentals?view=netcore-2.2)
* Content Source: [docs/standard/garbage-collection/fundamentals.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/garbage-collection/fundamentals.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @xisimao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@xisimao

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/standard/garbage-collection/fundamentals?view=netcore-2.2

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
