### ISSUE TITLE
无法找到locbaml工具的官方下载地址，里面的链接错误！

### ISSUE THREAD

**Issue by jasonfint** [dotnet/docs.zh-cn#435]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 72e544a8-3979-26ea-39fb-316eafa71cdb
* Version Independent ID: 5b84e3b3-e09f-be5d-8936-ed1ceb81203c
* Content: [如何：对应用程序进行本地化](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/advanced/how-to-localize-an-application)
* Content Source: [docs/framework/wpf/advanced/how-to-localize-an-application.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/advanced/how-to-localize-an-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @jasonfint
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #13946](https://github.com/dotnet/docs/issues/13946) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@jasonfint

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 -  https://github.com/dotnet/docs/issues/13946

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
