### ISSUE TITLE
类名class TestClass

### ISSUE THREAD

**Issue by dcr916759824** [dotnet/docs.zh-cn#454]
class TestClass
{
    public class Shape
   我认为Class TestClass 改成namespace  TestClass 可能更好
   

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 89022fe7-b2e3-5fb5-4930-d6bc5284081a
* Version Independent ID: 6a4f3ec1-e2eb-e046-d840-1c442276b3fb
* Content: [virtual - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/virtual#feedback)
* Content Source: [docs/csharp/language-reference/keywords/virtual.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/virtual.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
那样又要多写一个类放`static void Main`了

**Comment by srvbpigh** [comment]
Hello, @dcr916759824
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@dcr916759824
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
