### ISSUE TITLE
没有这些sdk啊

### ISSUE THREAD

**Issue by xyfy** [dotnet/docs.zh-cn#458]
我通过安装vs，没有显示很多个运行时和sdk在控制面板

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [删除 .NET Core 运行时和 SDK - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/versions/remove-runtime-sdk-versions?tabs=windows#feedback)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @xyfy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
没有那就没装呗

**Comment by xyfy** [comment]
我是说我有这些SDK，但是程序安装卸载里头没有



---原始邮件---
发件人: "谭九鼎"<notifications@github.com&gt;
发送时间: 2019年8月30日(星期五) 下午5:02
收件人: "dotnet/docs.zh-cn"<docs.zh-cn@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xyfy"<benguahao@foxmail.com&gt;;
主题: Re: [dotnet/docs.zh-cn] 没有这些sdk啊 (#458)



没有那就没装呗

**Comment by imba-tjd** [comment]
嗯……好像确实是这样，只有UWP的设置里有。

**Comment by CeciAc** [comment]
你好，@xyfy
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by xyfy** [comment]
你这个不就是文档问题吗？文档说可以通过程序卸载，实际安装的都没显示在程序列表里头。



---原始邮件---
发件人: "Cecilia Acevedo"<notifications@github.com&gt;
发送时间: 2019年8月30日(星期五) 晚上11:13
收件人: "dotnet/docs.zh-cn"<docs.zh-cn@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xyfy"<benguahao@foxmail.com&gt;;
主题: Re: [dotnet/docs.zh-cn] 没有这些sdk啊 (#458)



你好，@xyfy
 非常感谢你的参与。我们的团队只能回应与文档相关的反馈。&nbsp;
 
请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。&nbsp;
 
若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。&nbsp;
 
非常感谢你对我们的文章作出的贡献。&nbsp;&nbsp;
 
深深的祝福，&nbsp;
 Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@xyfy

非常感谢你的参与。

我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/14109 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
