### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by hanrai** [dotnet/docs.zh-cn#459]
4.将控件传输到非托管函数。翻译错误，应该是：将控制转移到非托管函数。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e096b54c-f52f-1f8e-7148-5f46d9f5f23e
* Version Independent ID: 8e41580d-9236-4b24-6430-c7d413bb78b5
* Content: [使用非托管 DLL 函数](https://docs.microsoft.com/zh-cn/dotnet/framework/interop/consuming-unmanaged-dll-functions)
* Content Source: [docs/framework/interop/consuming-unmanaged-dll-functions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/interop/consuming-unmanaged-dll-functions.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @hanrai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@hanrai

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/docs.zh-cn/pull/460
因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
