### ISSUE TITLE
mangled 翻译为修饰更合适

### ISSUE THREAD

**Issue by hanrai** [dotnet/docs.zh-cn#461]
mangled 翻译成损坏……这个我实在不能理解。翻译成修饰似乎更为合适，虽然社区通常把这个叫做粉碎（实际上似乎也确实如此），不过正式场合还是用修饰比较容易理解。
同样的 unmangled 翻译成未修饰比较好些。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 28649df2-57ac-bec0-b17d-03f1b0f1a44f
* Version Independent ID: 8b6a42c4-1163-d15c-ddde-1c7e647272a5
* Content: [指定字符集](https://docs.microsoft.com/zh-cn/dotnet/framework/interop/specifying-a-character-set)
* Content Source: [docs/framework/interop/specifying-a-character-set.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/interop/specifying-a-character-set.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @hanrai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
