### ISSUE TITLE
表格种“显示”应为“传递”

### ISSUE THREAD

**Issue by hanrai** [dotnet/docs.zh-cn#462]
原文也没有显示的意思。把显示换为传递，这样语义就是正确的。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d9466a98-6498-3816-8385-3fa97ce746e3
* Version Independent ID: b7eba3f0-803c-8895-56f6-633de8ec857d
* Content: [封送类、结构和联合](https://docs.microsoft.com/zh-cn/dotnet/framework/interop/marshaling-classes-structures-and-unions)
* Content Source: [docs/framework/interop/marshaling-classes-structures-and-unions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/interop/marshaling-classes-structures-and-unions.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @hanrai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@hanrai

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/docs.zh-cn/pull/463
因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
