### ISSUE TITLE
 error: cs7036. 更正：var employee2 = new Employee("Bob", 1200); 缺少参数

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs.zh-cn#464]
`var employee2 = new Employee("Bob", 1200); `

error: cs7036. 更正：缺少参数

should be:
`var employee2 = new Employee("Bob", 1200，0);`

---
PS: 
1, `var employee2 = new Employee("Bob", 1200); `    it's ok.

2, I have had some slip-ups in writing
the following is error:

`var employee2 = new SalesEmployee("Bob", 
                                1200);`

#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6adc020a-0a39-b4e2-902a-c0d776356b2e
* Version Independent ID: ff107003-885e-0876-bbaa-2fb25daa6369
* Content: [override 修饰符 - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/override)
* Content Source: [docs/csharp/language-reference/keywords/override.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/override.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @kinglionsz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
can't reproduce.

![图片](https://user-images.githubusercontent.com/24759802/64092715-7abd8d80-cd88-11e9-9bc2-d78d05bfcc19.png)

**Comment by kinglionsz** [comment]
> can't reproduce.
> 
> ![图片](https://user-images.githubusercontent.com/24759802/64092715-7abd8d80-cd88-11e9-9bc2-d78d05bfcc19.png)

tks,

but this is my report:

<img width="731" alt="Annotation 2019-09-02 135137" src="https://user-images.githubusercontent.com/51827261/64093038-64fc9800-cd89-11e9-864a-b9863971eaaa.png">


 Microsoft Visual Studio Professional 2019 Preview
Version 16.3.0 Preview 2.0
VisualStudio.16.Preview/16.3.0-pre.2.0+29209.152
Microsoft .NET Framework
Version 4.8.03921

**Comment by imba-tjd** [comment]
文档里的是

```
var employee2 = new Employee("Bob", 1200); 
```

你截图里的是
```
var employee2 = new SalesEmployee("Bob", 1200); 
```

这能一样吗

**Comment by kinglionsz** [comment]
> 文档里的是
> 
> ```
> var employee2 = new Employee("Bob", 1200); 
> ```
> 
> 你截图里的是
> 
> ```
> var employee2 = new SalesEmployee("Bob", 1200); 
> ```
> 
> 这能一样吗

👍😂,🤦‍♂️Thank you so much!
