### ISSUE TITLE
编程语言小结中functional-first应为函数优先而不是功能优先

### ISSUE THREAD

**Issue by hanrai** [dotnet/docs.zh-cn#465]
F#是函数式编程语言，funcaional在这种语境下多指函数而非功能。这里说的functional-first和后面的面向对象相对应，应该翻译为函数优先。这样本段可以理解为在主要支持函数式编程范式的同时，也支持面向对象编程范式。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 350a9ca4-1407-4f80-0e3c-05609687c014
* Version Independent ID: 6ae6a540-0822-5e2d-cf75-97f064fa0961
* Content: [.NET 教程](https://docs.microsoft.com/zh-cn/dotnet/standard/tour)
* Content Source: [docs/standard/tour.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/tour.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @hanrai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@hanrai

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：  https://docs.microsoft.com/zh-cn/dotnet/standard/tour

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
