### ISSUE TITLE
the download link is not available

### ISSUE THREAD

**Issue by RecardoKang** [dotnet/docs.zh-cn#467]
the first link "Microsoft Download Center" saies it is no longer available.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f8eaf243-2364-a015-4607-602d7696e09a
* Version Independent ID: 8beffb44-c588-6b0e-007d-c2b29ecdac1f
* Content: [Visual Basic 语言规范](https://docs.microsoft.com/zh-cn/dotnet/visual-basic/reference/language-specification/?view=netframework-4.8#feedback)
* Content Source: [docs/visual-basic/reference/language-specification/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/visual-basic/reference/language-specification/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @RecardoKang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @RecardoKang 

I tried it on my end and it leads me to the en-US download page.
Do you get the same result using a diferent browser?
Can you please provide a screenshot of the error you get?

Thanks in advance
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
![图片](https://user-images.githubusercontent.com/24759802/64262097-2967f680-cf60-11e9-88fc-0a461d15bb8b.png)

**Comment by CeciAc** [comment]
Thank you, @imba-tjd :)

**Comment by mairaw** [comment]
I did update the fwlink to go directly to the en-us page. I don't believe there's a localized version of the spec.

**Comment by CeciAc** [comment]
Hi @RecardoKang

Thank you for your feedback.
 
I'm closing this issue since it was already addressed as per above comment.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
