### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by vhvy** [dotnet/docs.zh-cn#469]
`如果程序存储在文件 example.cs 中，那么在 example.cs 编译完后，可以使用编译器的 /r 选项引用 acme.dll 程序集`
这句话中的 `example.cs 编译完后` 应翻译为`example.cs 编译时`

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 20935a57-1ba9-a5b8-0a30-cc68dac2e4e1
* Version Independent ID: 7c81da48-bf33-8c1a-f9fe-d02e056b2a07
* Content: [C# 程序结构 - C# 语言介绍](https://docs.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/program-structure#feedback)
* Content Source: [docs/csharp/tour-of-csharp/program-structure.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tour-of-csharp/program-structure.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @vhvy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@vhvy

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/docs.zh-cn/pull/470
因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
