### ISSUE TITLE
example code error 示例代码更正

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs.zh-cn#472]
示例代码 https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/join-clause#example：

错误一：
` Console.WriteLine("GroupJoin3: {0} items in 1 group", totalItems, groupJoinQuery3.Count());
`
应当更正为：
` Console.WriteLine("GroupJoin3: {0} items in {1} group", totalItems, groupJoinQuery3.Count());`

或者：
` Console.WriteLine("GroupJoin3: {0} items in 1 group", totalItems/*, groupJoinQuery3.Count()*/);`

错误二：
`Console.WriteLine("Group:", prodGrouping.Count());`
应当更正为：
`Console.WriteLine("Group{0}:", prodGrouping.Count());`

或者：
`Console.WriteLine("Group:"/*, prodGrouping.Count()*/);`

由此，运行结果也应当对应更正。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7f64bda9-3763-e0a0-fbb9-22f6fd50beca
* Version Independent ID: d552325f-7578-efb3-3f6d-927169181391
* Content: [join 子句 - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/join-clause#feedback)
* Content Source: [docs/csharp/language-reference/keywords/join-clause.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/join-clause.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @kinglionsz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@kinglionsz

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/samples/pull/1444
因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team

**Comment by kinglionsz** [comment]
> 你好，@kinglionsz
> 
> 非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 
> 
> 请查看问题 [dotnet/samples#1444](https://github.com/dotnet/samples/pull/1444)
> 因此我们将关闭这一重复的问题。 
> 
> 深深的祝福， 
> Microsoft DOCS International Team

Thank you for your reply but it seems that you have solved the issue which I found ,and not the repeat issue.
