### ISSUE TITLE
code output error: Uppercase letters: ABCDEFGHIJKLMNOPQRSTUVWXYZ

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs.zh-cn#474]
示例代码输出更正： https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/pointer-related-operators#pointer-element-access-operator-

https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/pointer-related-operators#pointer-element-access-operator-

`unsafe
{
    char* pointerToChars = stackalloc char[123];

    for (int i = 65; i < 123; i++)
    {
        pointerToChars[i] = (char)i;
    }

    Console.Write("Uppercase letters: ");
    for (int i = 65; i < 91; i++)
    {
        Console.Write(pointerToChars[i]);
    }
}
// Output:
// Uppercase letters: ABCDEFGHIJKLMNOPQRSTUVWXYZ`

实际输出：
Uppercase letters:
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
<img width="585" alt="char_array_pointer_output" src="https://user-images.githubusercontent.com/51827261/64577224-55470a00-d3ae-11e9-8fe7-98f53270525a.png">

<img width="422" alt="char_array_pointer_output_error" src="https://user-images.githubusercontent.com/51827261/64628590-3e42ff00-d424-11e9-942d-0af00eceab1e.png">

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9f615ca9-4bdb-38c9-26e2-21ed1218d524
* Version Independent ID: fc94240e-e933-efd2-263b-aa08d431dabb
* Content: [指针相关运算符 - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/pointer-related-operators#address-of-operator-)
* Content Source: [docs/csharp/language-reference/operators/pointer-related-operators.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/operators/pointer-related-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
为什么你运行的代码总是和网页上的不一样……

**Comment by srvbpigh** [comment]
Hello, @kinglionsz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by kinglionsz** [comment]
> 为什么你运行的代码总是和网页上的不一样……
> 
> You changed the code.

you can try.

**Comment by imba-tjd** [comment]
![图片](https://user-images.githubusercontent.com/24759802/64606451-dd520180-d3f8-11e9-8c8f-d35b3f717377.png)
![图片](https://user-images.githubusercontent.com/24759802/64606461-e347e280-d3f8-11e9-8199-1a399db9a2b5.png)
有啥好try的

**Comment by kinglionsz** [comment]
> ![图片](https://user-images.githubusercontent.com/24759802/64606451-dd520180-d3f8-11e9-8c8f-d35b3f717377.png)
> ![图片](https://user-images.githubusercontent.com/24759802/64606461-e347e280-d3f8-11e9-8199-1a399db9a2b5.png)
> 有啥好try的


> ![图片](https://user-images.githubusercontent.com/24759802/64606451-dd520180-d3f8-11e9-8c8f-d35b3f717377.png)
> ![图片](https://user-images.githubusercontent.com/24759802/64606461-e347e280-d3f8-11e9-8199-1a399db9a2b5.png)
> 有啥好try的

请你不要自以为是！你把代码敲进去看看结果再下结论好不好？
我增加的那行代码对你这个自以为是的来说那是个“坑”。

**Comment by kinglionsz** [comment]
Reference code is as follows：

`

            unsafe
            {
                char* pointerToChars = stackalloc char[123];

                for (int i = 65; i < 123; i++)
                {
                    pointerToChars[i] = (char)i;
                }

                string ss = "";
                Console.WriteLine("Uppercase letters: ");
                for (int i = 65; i < 91; i++)
                {
                    ss += pointerToChars[i];
                }
                Console.WriteLine(ss);
            }
            //  output:
            //  Uppercase letters:
            //  ABCDEFGHIJKLMNOPQRSTUVWXYZ

`

**Comment by kinglionsz** [comment]
<img width="913" alt="char_array_pointer_output_ok" src="https://user-images.githubusercontent.com/51827261/64627839-eeb00380-d422-11e9-902c-2efe924316de.png">

**Comment by kinglionsz** [comment]
@CeciAc @srvbpigh @jongalloway @imba-tjd

**Comment by CeciAc** [comment]
你好，@kinglionsz
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by kinglionsz** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/pointer-related-operators#pointer-element-access-operator-

###  1, the issue:

the code it's self  correct,but the output format is not expected


`
unsafe
{
    char* pointerToChars = stackalloc char[123];

    for (int i = 65; i < 123; i++)
    {
        pointerToChars[i] = (char)i;
    }

    Console.Write("Uppercase letters: ");
    for (int i = 65; i < 91; i++)
    {
        Console.Write(pointerToChars[i]);
    }
}
// Output:
// Uppercase letters: ABCDEFGHIJKLMNOPQRSTUVWXYZ

`
### The above code  `   pointerToChars[i] = (char)i;    ` output format is not  `  Uppercase letters: ABCDEFGHIJKLMNOPQRSTUVWXYZ  `  .in fact, this code output will be:

`
Uppercase letters:
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z

`

please see the screen snip:

<img width="422" alt="char_array_pointer_output_error" src="https://user-images.githubusercontent.com/51827261/64659900-addedb80-d470-11e9-9c84-72c903e68f86.png">


### 2, to obtain the expected ouput:

          Uppercase letters:
          ABCDEFGHIJKLMNOPQRSTUVWXYZ

### Reference code should be as follows:

`

        unsafe
        {
            char* pointerToChars = stackalloc char[123];

            for (int i = 65; i < 123; i++)
            {
                pointerToChars[i] = (char)i;
            }

            string ss = "";
            Console.WriteLine("Uppercase letters: ");
            for (int i = 65; i < 91; i++)
            {
                ss += pointerToChars[i];
            }
            Console.WriteLine(ss);
        }
        //  output:
        //  Uppercase letters:
        //  ABCDEFGHIJKLMNOPQRSTUVWXYZ
`
<img width="913" alt="char_array_pointer_output_ok" src="https://user-images.githubusercontent.com/51827261/64660603-b2f15a00-d473-11e9-8186-d933ff76ea39.png">

@CeciAc @srvbpigh @jongalloway @imba-tjd

**Comment by imba-tjd** [comment]
My last reply:

![image](https://user-images.githubusercontent.com/24759802/64669248-79c8e200-d493-11e9-821f-0a726969deb4.png)

As I said before. Your code is not the same as what it is in doc. You changed the code and got a different result, that's normal.

**Comment by pkulikov** [comment]
This issue in the main repo: dotnet/docs#14358

**Comment by kinglionsz** [comment]
I like code instead of copying the code😍

**Comment by kinglionsz** [comment]
> This issue in the main repo: [dotnet/docs#14358](https://github.com/dotnet/docs/issues/14358)

Yes, It was my fault. I typed Console.WriteLine instead of Console.Write because I type the code with IntelliSense and not copy the snippet.

Thank you so much and thank you for your time. @pkulikov

**Comment by kinglionsz** [comment]
> My last reply:
> 
> ![image](https://user-images.githubusercontent.com/24759802/64669248-79c8e200-d493-11e9-821f-0a726969deb4.png)
> 
> As I said before. Your code is not the same as what it is in doc. You changed the code and got a different result, that's normal.

I like code instead of copying the code😍
