### ISSUE TITLE
可能的描述错误

### ISSUE THREAD

**Issue by Shildreturn** [dotnet/docs.zh-cn#477]
”元组投影初始值设定项“章节，第一行的“一般情况下，元组投影初始值设定项使用元组初始化语句右侧的变量或字段名称。”是不是应该为“左侧的变量或字段名称”。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [元组类型 - C# 指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/tuples#feedback)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Shildreturn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Shildreturn

感谢你提交的语言方面的反馈。  

遗憾的是，我们语言团队评审你的反馈后，认为它不完全符合我们的接受条件，因为 [根据现有的英文来看，“右侧”并没有错。] 

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福， 
Microsoft DOCS International Team
