### ISSUE TITLE
Please add document on msbuild !!

### ISSUE THREAD

**Issue by John0King** [dotnet/docs.zh-cn#478]
csproj is part of .net ,  you can not use .net without it ,   now  I'd like to In-depth understanding more about msbuild and how to configurate the project

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 324ac109-634f-7e1b-6c22-694d711e7524
* Version Independent ID: 349e61a9-710b-02d9-9e64-a712f8d5e2cf
* Content: [.NET 指南](https://docs.microsoft.com/zh-cn/dotnet/standard/)
* Content Source: [docs/standard/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/index.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @cartermp
* Microsoft Alias: **ronpet**

**Comment by imba-tjd** [comment]
https://docs.microsoft.com/zh-cn/visualstudio/msbuild/msbuild

Searching before asking.

**Comment by John0King** [comment]
@imba-tjd I think the .net doc should also has   msbuild section doc,  at last should be a link point to the msbuild doc .
 and  I searched the msbuild doc , but not fond any detail doc on `PackageReference`,  and many things about the new `Microsoft.Net.Sdk`

**Comment by imba-tjd** [comment]
https://docs.microsoft.com/zh-cn/dotnet/core/tools/csproj

**Comment by mairaw** [comment]
We have plans to document the new SDK-style properties. You can follow https://github.com/dotnet/docs/issues/2642 to check for status updates.
