### ISSUE TITLE
Wrong warning

### ISSUE THREAD

**Issue by lirx-dvp** [dotnet/docs.zh-cn#480]
ArrayTestClass? naarr3 = null;

Console.WriteLine("naarr3: " + naarr3?.ToString());
Console.WriteLine();

naarr3 = new ArrayTestClass() { ATestP1 = 3, ATestP2 = "str3" };
Console.WriteLine("Reset naarr3 ?.tostring: " + naarr3?.ToString());
Console.WriteLine("Reset naarr3 .tostring: " + naarr3.ToString());//Wrong warning???
Console.WriteLine();

[*.cs]

# CS8618: 不可为 null 的字段未初始化。请考虑声明为可以为 null。
dotnet_diagnostic.CS8618.severity = error

# CS0251: 正在使用负值对数组编制索引
dotnet_diagnostic.CS0251.severity = error

# CS8625: 无法将 null 文本转换为不可为 null 的引用类型。
dotnet_diagnostic.CS8625.severity = error

# CS8619: 值中的引用类型的为 Null 性与目标类型不匹配。
dotnet_diagnostic.CS8619.severity = error

# CS8602: 取消引用可能出现的空引用。
dotnet_diagnostic.CS8602.severity = warning

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0dfe2629-7f0f-5ab7-6bf3-af84b050c425
* Version Independent ID: 17533d4f-fae1-0883-8838-4ba7c0727bc7
* Content: [使用可为空引用类型进行设计](https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/upgrade-to-nullable-references#feedback)
* Content Source: [docs/csharp/tutorials/upgrade-to-nullable-references.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tutorials/upgrade-to-nullable-references.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by lirx-dvp** [comment]
![1](https://user-images.githubusercontent.com/55911005/65813693-5203a900-e20b-11e9-9464-5946208ec8c2.png)

**Comment by srvbpigh** [comment]
Hello, @lirx-dvp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
You might need to file the issue at https://github.com/dotnet/roslyn

And I suggest you refining your article more clearly.

**Comment by lichasu** [comment]
你好，@lirx-dvp

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
