### ISSUE TITLE
使用 Blazor 进行完整堆栈 C# Web 开发

### ISSUE THREAD

**Issue by hiliyongke** [dotnet/docs.zh-cn#483]
应为
使用 Blazor 进行全栈 C# Web 开发

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d49bc05d-7c8e-5f89-aac5-d133225da4d5
* Version Independent ID: 2f831fc9-dfe6-15db-4ec6-00f59c2dacc2
* Content: [.NET Core 指南](https://docs.microsoft.com/zh-cn/dotnet/core/#feedback)
* Content Source: [docs/core/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/index.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by srvbpigh** [comment]
Hello, @hiliyongke
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
