### ISSUE TITLE
中文翻译错误

### ISSUE THREAD

**Issue by ArcherLew** [dotnet/docs.zh-cn#489]
[在此处输入反馈]

"下面的代码示例显示了 TestMethod 的定义和可用于异步调用 AsyncMethodCaller 的名称为 TestMethod 的委托。"
应该是 --->
"下面的代码示例显示了 TestMethod 的定义和可用于异步调用 TestMethod 的名称为 AsyncMethodCaller 的委托。"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 17acbfb3-4b90-a358-0417-2975f2475db4
* Version Independent ID: a6a6845f-e7cf-8c6f-65a8-04ed09f64a1e
* Content: [使用异步方式调用同步方法](https://docs.microsoft.com/zh-cn/dotnet/standard/asynchronous-programming-patterns/calling-synchronous-methods-asynchronously)
* Content Source: [docs/standard/asynchronous-programming-patterns/calling-synchronous-methods-asynchronously.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/asynchronous-programming-patterns/calling-synchronous-methods-asynchronously.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @ArcherLew
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@ArcherLew

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 #https://github.com/dotnet/docs.zh-cn/pull/490。因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
