### ISSUE TITLE
@No__t error notation

### ISSUE THREAD

**Issue by yaoyiqun** [dotnet/docs.zh-cn#491]
print @No__t error notation in Chinese Translation

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [如何使用C# -.NET 对 JSON 进行序列化和反序列化](https://docs.microsoft.com/zh-cn/dotnet/standard/serialization/system-text-json-how-to#feedback)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @yaoyiqun
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @yaoyiqun 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/dotnet/standard/serialization/system-text-json-how-to#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
