### ISSUE TITLE
图标表错误。反射和透明度下的表格列名重复写了 IsSecurityCritical

### ISSUE THREAD

**Issue by ND6** [dotnet/docs.zh-cn#492]
[在此处输入反馈]
该页图标表错误。反射和透明度下的表格列名重复写了 IsSecurityCritical，第二个IsSecurityCritical应该是IsSecuritySafeCritical.
![image](https://user-images.githubusercontent.com/40714554/67611894-5ef6c680-f7d0-11e9-8b23-c099cac78619.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b0feb127-a45f-ae3e-0193-4ab2fbd447aa
* Version Independent ID: db032a55-efe8-626e-457d-7fd4b2b8ff18
* Content: [反射的安全注意事项](https://docs.microsoft.com/zh-cn/dotnet/framework/reflection-and-codedom/security-considerations-for-reflection#feedback)
* Content Source: [docs/framework/reflection-and-codedom/security-considerations-for-reflection.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/reflection-and-codedom/security-considerations-for-reflection.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @ND6
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
