### ISSUE TITLE
]

### ISSUE THREAD

**Issue by vipwoke** [dotnet/docs.zh-cn#495]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ed4d3f75-0c09-2d1d-a2f6-0f2da89827da
* Version Independent ID: f8045ee7-8f1e-b3a0-a384-7f70f71fceff
* Content: [前台和后台线程](https://docs.microsoft.com/zh-cn/dotnet/standard/threading/foreground-and-background-threads)
* Content Source: [docs/standard/threading/foreground-and-background-threads.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/threading/foreground-and-background-threads.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @vipwoke
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@vipwoke
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？
顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@vipwoke
再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。
顺祝商祺！
Microsoft DOCS 国际团队
