### ISSUE TITLE
内插字符串符号错误

### ISSUE THREAD

**Issue by Sunnie-Shine** [dotnet/docs.zh-cn#499]
第一个示例中，两个使用内插字符串来表示的输出结果集是“$"{v.ID:-5}{v.Name}"”和“$"{v.CategoryID:-5}{v.Product}"”，但内插字符串的冒号后写的是格式化字符串，而-5表示对齐位置，故应把冒号“:”更改为逗号“,”。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bc1c6a95-14fb-596f-c783-dd9598ffca22
* Version Independent ID: 5ab6cb23-3eb0-5a7f-b43f-9d0de71fdf8b
* Content: [执行自定义联接操作（C# 中的 LINQ）](https://docs.microsoft.com/zh-cn/dotnet/csharp/linq/perform-custom-join-operations#feedback)
* Content Source: [docs/csharp/linq/perform-custom-join-operations.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/linq/perform-custom-join-operations.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Sunnie-Shine
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Sunnie-Shine

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/samples/pull/1766
因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
