### ISSUE TITLE
"Object and Collection Initializer" translation

### ISSUE THREAD

**Issue by ZSkycat** [dotnet/docs.zh-cn#50]
[对象和集合初始值设定项（C# 编程指南）](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers)

`Initializer` 翻译为 `初始值设定项` 非常拗口而且不直观。
个人认为翻译为 `初始化器` 会更且当些。

大家觉得呢？

**Comment by nokura** [comment]
Internal Reference: Verbatim bug#1183636

**Comment by CeciAc** [comment]
This term change was rejected in the verbatim triage. Please close this issue.
