### ISSUE TITLE
中文版“反射”的翻译有误

### ISSUE THREAD

**Issue by imaginezz** [dotnet/docs.zh-cn#500]
“反射”在目录中被翻译成了“映像”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c8bc41f1-c2f4-3d82-d65b-e986735162bd
* Version Independent ID: 1b8ea375-81a3-caef-f51a-f08635c6610a
* Content: [反射 (C#)](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/concepts/reflection#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/reflection.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/concepts/reflection.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @imaginezz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@imaginezz

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 https://github.com/dotnet/docs.zh-cn/pull/501 因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
