### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by 1009058470** [dotnet/docs.zh-cn#504]
例子的链接失效 访问不到资源

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f6505730-911e-b836-01a1-0b0084851d95
* Version Independent ID: b107ea00-08c9-75ef-5cb7-7bad31176e03
* Content: [取消一个异步任务或一组任务 (C#)](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks)
* Content Source: [docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/concepts/async/cancel-an-async-task-or-a-list-of-tasks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
dup of https://github.com/dotnet/docs/issues/13599

**Comment by srvbpigh** [comment]
Hello, @1009058470
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@1009058470

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 #https://github.com/dotnet/docs/issues/13599
因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
