### ISSUE TITLE
一直卡在Restore build script dependent packages怎么办

### ISSUE THREAD

**Issue by xxf2103625** [dotnet/docs.zh-cn#506]
myget.org里面的包复制到浏览器可以下载，但是sh里一直超时，可以绕过下载直接用本地nuget包吗？

**Comment by srvbpigh** [comment]
Hello, @xxf2103625
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@xxf2103625 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
