### ISSUE TITLE
NET修复失败+安装失败

### ISSUE THREAD

**Issue by lirener** [dotnet/docs.zh-cn#507]
在windows server 2019上 不小心用DISM++删除了 NET4.7后 无法安装回来 这个工具太旧了 无法修复
从官网下载 NET4.7.2提示已经安装更高版本 安装NET4.8提示证书弃用 都无法修复安装！在ISO里面找不到netfx4的源

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 567666ce-6b1c-ea9b-aa9e-eae9da4f9485
* Version Independent ID: f2e94c72-459b-c8f1-7eec-73e7d4197f4d
* Content: [修复 .NET Framework](https://docs.microsoft.com/zh-cn/dotnet/framework/install/repair#feedback)
* Content Source: [docs/framework/install/repair.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/install/repair.md)
* Product: **dotnet-framework**
* Technology: **dotnet-install**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by lirener** [comment]
[FixDotNet20191212204625449.cab.zip](https://github.com/dotnet/docs.zh-cn/files/3957797/FixDotNet20191212204625449.cab.zip)

已经测试了官网最新的工具 仍然无法解决问题……
微软 .NET 框架修复工具可用【仍然无法修复】
https://support.microsoft.com/zh-cn/help/2698555/microsoft-net-framework-repair-tool-is-available

**Comment by srvbpigh** [comment]
Hello, @lirener
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@lirener

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
