### ISSUE TITLE
I'm creating a webapi template for dotnet core3.1

### ISSUE THREAD

**Issue by WangJunZzz** [dotnet/docs.zh-cn#513]
[在此处输入反馈]
This is my .csproj configuration.
![image](https://user-images.githubusercontent.com/25657426/71435467-1736e180-2724-11ea-9eb6-db6b6e251f4d.png)
This is my project structure.
![image](https://user-images.githubusercontent.com/25657426/71435507-3e8dae80-2724-11ea-8345-7ce79841a303.png)
now,I execute the following command
```bash
dotnet nuget push .\TestTemplate.Api.3.1.0.nupkg -k kTPp8jzi5cAti7Nz/5UQb1fQV0GRr/C96qkgWWS3QMGJ56UfW1syjZOXEUVY0I6aGp8UPGmI1t+3nkBJrJBZIHA== -s http://120.77.250.112:8031/nuget
# result :Push success.
```
then,i Installation template
```bash
dotnet  new -i  Fairhr.WebApi  --nuget-source http://120.77.250.112:8031/nuget
```
![image](https://user-images.githubusercontent.com/25657426/71435648-da1f1f00-2724-11ea-8e33-b045c6e508c9.png)
No error message,but There is no fairhr.webapi in the template.
What causes this

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4e7deb06-37bb-b659-7cf3-9c47a91e065e
* Version Independent ID: d6e6f989-3956-6a0e-5e9c-fb3d1f9bd751
* Content: [dotnet new 自定义模板 - .NET Core CLI](https://docs.microsoft.com/zh-cn/dotnet/core/tools/custom-templates)
* Content Source: [docs/core/tools/custom-templates.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/tools/custom-templates.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @WangJunZzz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by WangJunZzz** [comment]
Got the problem，Add file ignore
<file src="content\**\**" target="content" exclude="content\.vs\**;content\**\bin\**;;content\**\obj\**" />

**Comment by Thraka** [comment]
@WangJunZzz Do you mean you solved the problem?

**Comment by WangJunZzz** [comment]
@Thraka yes, solved.
