### ISSUE TITLE
@$ 无效

### ISSUE THREAD

**Issue by dsaewq321** [dotnet/docs.zh-cn#518]
关于“ $@"..." 和 @$"..." 均为有效的内插逐字字符串。“，其中@$无效吧，虽然看到有人这样写，但我代码拉下来就报错了：
-- 错误	CS8401	若要对内插逐字字符串使用 "@$" 而不是 "$@"，请使用语言版本 8.0 或更高版本。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5e3c4c67-250d-50ac-35e7-b11a20d13ba0
* Version Independent ID: 2dab9569-8748-1325-d9b7-78c3f728deef
* Content: [C# 中的字符串内插](https://docs.microsoft.com/zh-cn/dotnet/csharp/tutorials/string-interpolation#feedback)
* Content Source: [docs/csharp/tutorials/string-interpolation.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tutorials/string-interpolation.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
你还必须证明你用的是8.0，否则你的无效是无效的

**Comment by srvbpigh** [comment]
Hello, @dsaewq321
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #16552](https://github.com/dotnet/docs/issues/16552) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@dsaewq321 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/16552。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
