### ISSUE TITLE
这是一个好文档

### ISSUE THREAD

**Issue by hushichao-encootech** [dotnet/docs.zh-cn#519]
这是一个好文档

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 85eba478-0374-bb9b-8fa7-d5cf7d520603
* Version Independent ID: 89967250-8c3b-1999-078f-94ad7518ed49
* Content: [.NET Core 应用程序部署 - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/deploying/index)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @hushichao-encootech
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@hushichao-encootech 

非常感谢你提供反馈。很高兴我们的文档满足你的期望。 
欢迎提供宝贵的反馈，以便我们继续改进体验。 


深深的祝福， 
Microsoft DOCS International Team
