### ISSUE TITLE
有非常多的占位符未替换成实际值

### ISSUE THREAD

**Issue by Sod-Momas** [dotnet/docs.zh-cn#520]
[在此处输入反馈]

文档中在大量 `@no__t ` 开头的名词, 初步猜测是变量占位符, 请问是否编写未完成导致的? 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e783650c-e063-e268-316e-564362cb1e37
* Version Independent ID: aa9f4996-cab4-0bed-6452-213342453785
* Content: [表达式Expressions - C# language specification](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/language-specification/expressions#feedback)
* Content Source: [spec/expressions.md](https://github.com/dotnet/csharplang.zh-cn/blob/1b022181a0a6e3e4fc5d78d37e6a33eca5161032/spec/expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Sod-Momas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
感谢你的反馈。  

我们的工程团队已评审并接受你的建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/language-specification/expressions#feedback。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
