### ISSUE TITLE
The title of the translation in chinese is wrong

### ISSUE THREAD

**Issue by slobber** [dotnet/docs.zh-cn#521]
"如何从 Newtonsoft.json 迁移到 system.exception" 应该为 "如何从newtonsoft.json迁移到 System.Text.Json"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [从 Newtonsoft.json 迁移到 system.exception-.NET](https://docs.microsoft.com/zh-cn/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#feedback)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @slobber
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
This issue also exists in some other localized repos. What's interesting is that the error text are not the same.

```
zh-tw: System.web. Json
ja-jp: system.string
ko-kr: System.object
```

This article is machine-translated. I'll only fix this one.

**Comment by CeciAc** [comment]
Hello, @slobber 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/dotnet/docs/issues/16688
 For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
