### ISSUE TITLE
文章开头部分最后一个对比位置错误

### ISSUE THREAD

**Issue by maanshancss** [dotnet/docs.zh-cn#533]
ByteString 是Protobuf 类型,而bytes 是C#的字节数组,写反了

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c2a41d02-3084-c31e-98ed-2bd786c7a301
* Version Independent ID: 31a20696-f326-63c3-77d1-f3cfc0aa589c
* Content: [Protobuf 标量数据类型-WCF 开发人员 gRPC](https://docs.microsoft.com/zh-cn/dotnet/architecture/grpc-for-wcf-developers/protobuf-data-types#feedback)
* Content Source: [docs/architecture/grpc-for-wcf-developers/protobuf-data-types.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/architecture/grpc-for-wcf-developers/protobuf-data-types.md)
* Product: **dotnet-architecture**
* Technology: **grpc**
* GitHub Login: @shirhatti
* Microsoft Alias: **soshir**

**Comment by srvbpigh** [comment]
Hello, @maanshancss
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
你好，@maanshancss， 

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by maanshancss** [comment]
Sorry,I was  wrong
