### ISSUE TITLE
主题的颜色有点少

### ISSUE THREAD

**Issue by Elliot-zjy** [dotnet/docs.zh-cn#536]
黑色的 白字太亮了，全白色 页面看的很疲劳，高对比度 更刺眼，希望能增加 几个  比较温和的颜色，比如 浅绿色  羊皮卷色

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 13c78b71-c023-5c22-f2de-accd4a6fa7e5
* Version Independent ID: 73a112db-0e66-0697-b4a3-9b88cbd981fc
* Content: [C# 委托 - C# 语言介绍](https://docs.microsoft.com/zh-cn/dotnet/csharp/tour-of-csharp/delegates#feedback)
* Content Source: [docs/csharp/tour-of-csharp/delegates.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/tour-of-csharp/delegates.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Elliot-zjy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #17458](https://github.com/dotnet/docs/issues/17458) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@Elliot-zjy 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/17458。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
