### ISSUE TITLE
C# 参考页面中关于C# 语言规范的链接指向错误

### ISSUE THREAD

**Issue by sgkoishi** [dotnet/docs.zh-cn#538]
[C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/)页面内C# 6.0-8.0的语言规范指向404。
https://github.com/dotnet/docs.zh-cn/blob/16fcbf703712b6f5db112190ee3a1f79f5524b45/docs/csharp/language-reference/index.md#L42
https://github.com/dotnet/docs.zh-cn/blob/16fcbf703712b6f5db112190ee3a1f79f5524b45/docs/csharp/language-reference/index.md#L47
https://github.com/dotnet/docs.zh-cn/blob/16fcbf703712b6f5db112190ee3a1f79f5524b45/docs/csharp/language-reference/index.md#L50
https://github.com/dotnet/docs.zh-cn/blob/16fcbf703712b6f5db112190ee3a1f79f5524b45/docs/csharp/language-reference/index.md#L53
https://github.com/dotnet/docs.zh-cn/blob/16fcbf703712b6f5db112190ee3a1f79f5524b45/docs/csharp/language-reference/index.md#L56
https://github.com/dotnet/docs.zh-cn/blob/16fcbf703712b6f5db112190ee3a1f79f5524b45/docs/csharp/language-reference/index.md#L59

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a60b6e17-36cf-bd6c-1b76-d38f1760a816
* Version Independent ID: 0fdeaa81-c3c2-c290-224e-792fcee9b297
* Content: [C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/)
* Content Source: [docs/csharp/language-reference/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @sgkoishi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@JasonCard can you please check this issue?
the contributor is reporting several 404 pages but we don't have the files (nor folders) to fix. 

@DavidPrio

**Comment by DavidPrio** [comment]
Hi @JasonCard @SunnyDeng we believe this is a source issue (or repo setup issue), since repo files/folders are not present in corresponding target repo/branch. Can you please check and confirm? Thanks!

**Comment by JasonCard** [comment]
@CeciAc @DavidPrio Thank you for checking. Those links are referencing [another source repo](https://github.com/dotnet/csharplang/tree/master/proposals) that was only partially localized, so I've updated auto-queries to localize the linked articles. Will update when this issue is resolved.
cc @sgkoishi @SunnyDeng

**Comment by JasonCard** [comment]
@sgkoishi Thank you for reporting this issue. The linked articles are now localized (machine translated) and broken links are fixed. Please let me know if you still see any similar issues.
cc @CeciAc
