### ISSUE TITLE
How to retrain a single zip model file?

### ISSUE THREAD

**Issue by lzmj** [dotnet/docs.zh-cn#539]
When saving a model, it is a single zip file. How can I retrain the model after loading a single zip model file?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0366cc46-bc07-44fd-72d9-d37b40bd5eca
* Version Independent ID: 5c20d041-f946-d7c8-b0b5-7bee96e90282
* Content: [重新训练模型 - ML.NET](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/how-to-guides/retrain-model-ml-net#feedback)
* Content Source: [docs/machine-learning/how-to-guides/retrain-model-ml-net.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/machine-learning/how-to-guides/retrain-model-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by srvbpigh** [comment]
Hello, @lzmj
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by luisquintanilla** [comment]
Hi @lzmj 

The process is the same. In this case, they are separated into two pipelines to make it easier to access the trainer. However, in a similar manner, you would get the `LastTransformer` from an ITransformer / TransformerChain. This assumes though that the last step in your pipeline is a trainer and that the trainer allows retraining (see the list of trainers that allow retraining in the how-to guide).

**Comment by CeciAc** [comment]
Hello, @lzmj 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
