### ISSUE TITLE
Translation error / 翻译错误

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs.zh-cn#553]
@scighost commented on [Thu Apr 09 2020](https://github.com/dotnet/docs.de-de/issues/182)

原文 / Original text：AccessTheWebAsync can't continue until getStringTask is complete.
错误译文 / Fault translation：在 AccessTheWebAsync 完成之前，getStringTask 无法继续。
应改为 / Change to：在 getStringTask 完成之前，AccessTheWebAsync 无法继续。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fbd97c63-2887-1891-fb08-9cd78659c2db
* Version Independent ID: 1ae4494a-ca0b-a1da-cdcf-522ef79e0fc5
* Content: [使用 Async和 Await 的任务异步编程模型 (TAP) (C#)](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model)
* Content Source: [docs/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/concepts/async/task-asynchronous-programming-model.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Thu Apr 09 2020](https://github.com/dotnet/docs.de-de/issues/182#issuecomment-611549522)

Hello, @scighost
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@CeciAc commented on [Thu Apr 09 2020](https://github.com/dotnet/docs.de-de/issues/182#issuecomment-611553441)

@JasonCard same bug than https://github.com/dotnet/docs.de-de/issues/180 

---

@CeciAc commented on [Thu Apr 09 2020](https://github.com/dotnet/docs.de-de/issues/182#issuecomment-611553803)

Issue moved to [dotnet/docs.zh-tw #278](https://github.com/dotnet/docs.zh-tw/issues/278) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @CeciAc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@CeciAc  

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
