### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by huhubun** [dotnet/docs.zh-cn#557]
以下内容应保持英文
- “.NET 标准” .NET Standard
- “.NET 框架” .NET Framework
- “.NET 核心” .NET Core
- “牛顿软.Json” Newtonsoft.Json
-  “文本.Json” System.Text.Json
- （第一个）“打开序列化” `OnDeserializing` （注：应该使用行内代码）
- （第二个）“打开序列化” `OnDeserialized`
- “在序列化时” `OnSerializing`
- “序列化时” `OnSerialized`
- “系统.运行时.序列化” System.Runtime.Serialization
- “&lt;ReadOnlySequence 字节&gt;”、“ReadOnlySpan&lt;字节&gt;”等”字节“ 应该为 -&gt; byte

以下内容翻译错误或不准确
- “允许尾随全球设置” -&gt; “允许尾随逗号全局设置”
- “使用非字符串`Dictionary`键反序列化” -&gt; “反序列化键为非字符串的 `Dictionary`”
- “内部和私有财产设置者和获取者” -&gt; “内部和私有属性的 `get` 和 `set` 访问器”
- “System.Text.Json默认情况下严格，避免代表呼叫者进行任何猜测或解释，强调确定性行为。” -&gt; “System.Text.Json默认情况下是严格的，避免代表调用者进行任何猜测或解释，强调确定性行为。”
- “系统.运行时.序列化属性” -&gt; “System.Runtime.Serialization 特性”
- “JsonDocument 是 I 一次性的” -&gt; “JsonDocument 是可释放的” 或 “JsonDocument 实现了 IDisposable”
- “Newtonsoft.Json提供了几种控制 属性DateTime和DateTimeOffset类型序列化和非序列化的方法” -&gt; “Newtonsoft.Json 提供了几种方式来控制 `DateTime` 和 `DateTimeOffset` 类型属性的序列化和反序列化”

格式和符号错乱
- 很多行内代码都错乱了，例如  
“最小字符转义”一节：
```
它不会将它们替换为\uxxxx``xxxx字符的代码点
```
  
 “对象属性的序列化”一节：
```
并返回存储string的 、、、、boolean``DateTime``long``double或作为盒装对象
```
- 无效的引用
```
通过在类中使用属性或将转换器添加到&lt;xref:[!OP.NO-LOC(System.Text.Json)].JsonSerializerOptions.Converters&gt;集合中来注册此自定义转换器。
```
- 不应该使用中文符号
   - “ISO 8601-1：2019” -&gt; “ISO 8601-1:2019”

我暂时没有提交 PR，因为我认为有一些共性的问题（例如我在”以下内容应保持英文“和”格式和符号错乱“中提到的）在其他文档中也存在，相信你们有更好的办来检测和并修复翻译程序，让以后翻译的文档不再出现类似的问题。  
如果需要，请告诉我，我会对本文档提交 PR。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6b74d77c-33e1-d44c-18c6-bd0b612f74de
* Version Independent ID: 9c6a7135-eb75-21a9-1d27-0880459523ca
* Content: [从Newtonsoft.Json迁移到System.Text.Json- .NET](https://docs.microsoft.com/zh-cn/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to)
* Content Source: [docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to.md)
* Product: **dotnet**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @huhubun
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@huhubun

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队

**Comment by JasonCard** [comment]
Hi @huhubun, 
Thank you for your feedback.
We are aware of some general Machine Translation issues that you mentioned and currently working on those improvements. 
In the meantime, I'm planning to Human Translate the content under /dotnet/standard/serialization soon.

Best regards,
Jason
