### ISSUE TITLE
一个小的翻译错误

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs.zh-cn#566]
@scighost commented on [Thu Apr 09 2020](https://github.com/dotnet/docs.de-de/issues/181)

“表达式lambda”部分：
原文：A lambda expression that has one parameter and returns a value can be converted to a Func<T,TResult> delegate.
现译文：有 1 个参数且不返回值的 Lambda 表达式可转换为 Func<T,TResult> 委托。

returns a value  -  不返回值

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 567260f8-0f94-b48c-8344-0d9780ab4448
* Version Independent ID: 1bebe367-5b93-0b83-72f5-bdf31d65ef5d
* Content: [Lambda 表达式 - C# 编程指南](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@srvbpigh commented on [Thu Apr 09 2020](https://github.com/dotnet/docs.de-de/issues/181#issuecomment-611317489)

Hello, @scighost
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @CeciAc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@CeciAc  

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
