### ISSUE TITLE
为啥要翻译关键字

### ISSUE THREAD

**Issue by dsfag** [dotnet/docs.zh-cn#568]
接口	内部 全新这些关键字不用翻译吧。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [C# 关键字](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/#feedback)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @dsfag
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@dsfag  

感谢你提交的语言方面的反馈。   

遗憾的是，我们语言团队评审你的反馈后，认为它不完全符合我们的接受条件，因为 In current zh-CN site, these are left in EN. This is FP.  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。   

深深的祝福，  
Microsoft DOCS International Team
