### ISSUE TITLE
翻译有误

### ISSUE THREAD

**Issue by Kudaye** [dotnet/docs.zh-cn#571]
https://docs.microsoft.com/zh-cn/dotnet/csharp/async#feedback
If the work you have is I/O-bound, use async and await without Task.Run. You should not use the Task Parallel Library. The reason for this is outlined in the Async in Depth article.
如果你的工作为 I/O 绑定，请使用 和（而不使用 async）await Task.Run。 不应使用任务并行库 。 相关原因在深入了解异步的文章中说明。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 07ed82a3-99c1-0893-4e81-d095b4757ecc
* Version Independent ID: 3765200b-43e5-441c-b290-709c34dd2f6d
* Content: [异步编程 - C#](https://docs.microsoft.com/zh-cn/dotnet/csharp/async#feedback)
* Content Source: [docs/csharp/async.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/async.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Kudaye
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@Kudaye  

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/async#feedback。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
