### ISSUE TITLE
翻译有误

### ISSUE THREAD

**Issue by guZoujyQ** [dotnet/docs.zh-cn#574]
原文：
If the work you have is CPU-bound and you care about responsiveness, use async and await but spawn the work off on another thread with Task.Run.
现翻译：
如果你的工作为 CPU 绑定，并且你重视响应能力，请使用 和，并在另一个线程上使用 async 生成工作。await Task.Run
应改为：
如果你的工作为 CPU 绑定，并且你重视响应能力，请使用 async 和 await ，但需要用 Task.Run 把工作放到另一个线程中。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 07ed82a3-99c1-0893-4e81-d095b4757ecc
* Version Independent ID: 3765200b-43e5-441c-b290-709c34dd2f6d
* Content: [异步编程 - C#](https://docs.microsoft.com/zh-cn/dotnet/csharp/async#feedback)
* Content Source: [docs/csharp/async.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/async.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @guZoujyQ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
