### ISSUE TITLE
在Ubuntu20.04上无法安装

### ISSUE THREAD

**Issue by F-Unction** [dotnet/docs.zh-cn#576]
dotnet-sdk-3.1 -&gt;  dotnet-runtime-3.1  -&gt; dotnet-runtime-deps-3.1 -&gt;  libicu63
但是系统中只有 libicu66

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [在 Ubuntu 19.10 包管理器上安装 .NET Core - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/install/linux-package-manager-ubuntu-1910#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @F-Unction
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Thraka** [comment]
Duplicate of #17638

**Comment by Thraka** [comment]
Duplicate of dotnet/docs#17638
