### ISSUE TITLE
Is there a PDF download link ？

### ISSUE THREAD

**Issue by Inzaghi2012** [dotnet/docs.zh-cn#58]
I can find the PDF download link in the original version. (Left bottom corner of the page)
https://docs.microsoft.com/en-us/dotnet/welcome 

But it could not be found in the Chinese version.
https://docs.microsoft.com/zh-cn/dotnet/welcome

Any suggestion ?

**Comment by mairaw** [comment]
@nokura the localized repos are not configured to support PDF builds. Is this just a matter of updating the configuration or the build doesn't support PDF builds? /cc @SonjaSaltzman

**Comment by nokura** [comment]
Thank you for your question. PDF of localized version is currently being tested. When we verify it works correctly, we will enable the download button.  I am checking the estimated completion date and get back to you.

**Comment by CeciAc** [comment]
Hi @nokura 
Is there any update on this?

**Comment by SonjaSaltzman** [comment]
Adding @nokura and @swgupt - can these loc repos be enabled for pdf download?

**Comment by nokura** [comment]
We are still testing the localized PDF.  Once I see the estimated PDF available date, I will share the info here.

**Comment by nokura** [comment]
Thank you for your patience. We are still testing Localized PDF downloads. I will update once it gets enabled.

**Comment by nokura** [comment]
Hello @Inzaghi2012 
We are still working on ennoblement of localized PDF downloads. I am sorry for your inconvenience and will get back to you when it is implemented.
Kind regards,
Microsoft DOCS International Team

**Comment by nokura** [comment]
Hello @Inzaghi2012 
I would like to give you some updates on our side. Due to some technical issues, we have postponed the PDF downloads enablement .I am sorry for your inconvenience and appreciate your patience.
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hi @nokura 

Is there an update on this issue?

Thanks!

**Comment by nokura** [comment]
Hello @Inzaghi2012 
We are still working on Loc PDF improvement and no concrete schedule to complete it. We will enable localized PDF downloads as soon as we implement the new build process. Please allow me to close this GitHub issue at this point.

**Comment by L261173157** [comment]
thank you for your working
