### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by CadenJi** [dotnet/docs.zh-cn#583]
“缓存的计算属性”部分
原文：You modify the set accessors of the FirstName and LastName property so that the fullName field is calculated again
现译文：修改 set 和 FirstName 属性的 LastName 访问器，以便重新计算 fullName 字段

应该翻译为：修改 FirstName 和 LastName 属性的 set 访问器，以便重新计算fullName 字段 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1e614217-286d-2231-f0c7-d37e5a31b2d5
* Version Independent ID: 070d932f-bc38-a766-37cc-ec861e74be1c
* Content: [属性](https://docs.microsoft.com/zh-cn/dotnet/csharp/properties)
* Content Source: [docs/csharp/properties.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/properties.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @CadenJi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
This has been fixed in https://github.com/dotnet/docs.zh-cn/commit/61e6e4d19471a9f853a4fa1ec820194af8a845e5#diff-20fa508b2538e9f266a716522076d0caR122

**Comment by CeciAc** [comment]
你好，@CadenJi

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/properties

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
