### ISSUE TITLE
Ubuntu20.04已经推出，请加入“在Ubuntu20.04包管理器上安装.NET Core”的文档

### ISSUE THREAD

**Issue by developerdong** [dotnet/docs.zh-cn#584]
Ubuntu20.04已经推出，请加入“在Ubuntu20.04包管理器上安装.NET Core”的文档

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [在 Ubuntu 18.04 包管理器上安装 .NET Core - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/install/linux-package-manager-ubuntu-1804)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by imba-tjd** [comment]
dup of https://github.com/dotnet/docs/issues/17638

**Comment by srvbpigh** [comment]
Hello, @developerdong
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@developerdong

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。  

请查看问题 https://github.com/dotnet/docs/issues/17638
因此我们将关闭这一重复的问题。  
 
深深的祝福，  

Microsoft DOCS International Team
