### ISSUE TITLE
xml tag content was accidentally translated

### ISSUE THREAD

**Issue by Flithor** [dotnet/docs.zh-cn#589]
Title
> &lt;gcAllow非常大的对象&gt;元素

and tree
```
<配置>
  <运行时>
    <gcAllow 非常大的对象>
```
this issues was existed in all of sub item in page:
https://docs.microsoft.com/zh-cn/dotnet/framework/configure-apps/file-schema/runtime/

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2e093d16-79e3-e4eb-323f-4e4ef7fe677b
* Version Independent ID: f673a7d5-3db0-3bb2-5077-a3186871fc71
* Content: [&lt;gcAllowVeryLargeObjects&gt; 元素](https://docs.microsoft.com/zh-cn/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element?view=netcore-3.1)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @Flithor
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by gewarren** [comment]
@Flithor Thanks for letting us know. Loc team - the best solution here might be to put the XML inside a code fence.

**Comment by CeciAc** [comment]
Hello @Flithor 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team

**Comment by gewarren** [comment]
@CeciAc This is an issue of text that shouldn't have been translated, so I'll move it to the main (English) repo.

**Comment by JasonCard** [comment]
@gewarren I agree, code fencing would work to block XML tags from localization. Reopening the issue to move to dotnet/docs.
cc @CeciAc

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#18360

**Comment by gewarren** [comment]
#please-close
