### ISSUE TITLE
Deconstruction 被错误翻译为“析构”

### ISSUE THREAD

**Issue by GrizzlyHills** [dotnet/docs.zh-cn#592]
Deconstruction 的中文翻译应该为“解构”或者“拆析”，被翻译为“析构”是错误的。

“析构”对应的英文原意是 destruction  或者 finalization。

所以，这种错误对使用中文阅读的初学者造成了基本概念层面的误导，是较为严重的翻译错误。

目前，我发现这些错误出现在 https://docs.microsoft.com/zh-cn/dotnet/csharp/tuples 和 https://docs.microsoft.com/zh-cn/dotnet/csharp/deconstruct 中。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ec91dfa8-265f-a220-fe14-14047375ee93
* Version Independent ID: b2afe72f-5b30-8938-7b64-9f45056df36a
* Content: [析构元组和其他类型](https://docs.microsoft.com/zh-cn/dotnet/csharp/deconstruct)
* Content Source: [docs/csharp/deconstruct.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/deconstruct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @GrizzlyHills
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@GrizzlyHills

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。  

请查看问题 #591 
因此我们将关闭这一重复的问题。  

深深的祝福，  

Microsoft DOCS International Team
