### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by DaseinPhaos** [dotnet/docs.zh-cn#596]
`enclosing type`被翻译为`封闭类型`，让人联想到`closed type`，造成了疑惑。拟翻译为`封入类型`/`嵌入类型`?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1ea44b60-f807-c645-f52e-d4e0de5e08a8
* Version Independent ID: 8fcd1057-5983-59ad-ac65-13ac3d1119d7
* Content: [编译器错误 CS0556](https://docs.microsoft.com/zh-cn/dotnet/csharp/misc/cs0556#feedback)
* Content Source: [docs/csharp/misc/cs0556.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/misc/cs0556.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @DaseinPhaos
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@DaseinPhaos

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队
