### ISSUE TITLE
预测结果和概率对不上

### ISSUE THREAD

**Issue by JohnnyZhang0628** [dotnet/docs.zh-cn#597]
开始测试评估模型......
正确度: 76.47%
可信度: 93.88%
F1Score: 47.33%
文本: 量大，好吃 | 情感预测: 消极 | 概率: 0.09182736

消极的概率为0.09%，为啥预测的为消极而不是积极的呢？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [教程：分析网站评论 - 二元分类 - ML.NET](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/sentiment-analysis#feedback)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by srvbpigh** [comment]
Hello, @JohnnyZhang0628
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@JohnnyZhang0628

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。 

如果你有任何与文档相关的反馈，请通过此渠道进行记录。 

我们非常感谢你对我们的文章的贡献。 

Microsoft DOCS 国际团队

**Comment by JohnnyZhang0628** [comment]
> 你好，@JohnnyZhang0628
> 
> 非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。
> 
> 如果你有任何与文档相关的反馈，请通过此渠道进行记录。
> 
> 我们非常感谢你对我们的文章的贡献。
> 
> Microsoft DOCS 国际团队

![image](https://user-images.githubusercontent.com/28375774/82274310-65d66800-99b2-11ea-90e6-ffd3fdffb9df.png)
您好，文档页面的反馈功能不能使用，所以我在github上反馈问题。
以下是我的代码
`string _dataPath = Path.Combine(Environment.CurrentDirectory, "Data", "food.txt");
            MLContext mlContext = new MLContext();

            // 加载数据
            IDataView dataView = mlContext.Data.LoadFromTextFile<SentimentData>(_dataPath, hasHeader: false);
            var splitDataView = mlContext.Data.TrainTestSplit(dataView, testFraction: 0.2);

            // 提取和转换数据
            var pipeline = mlContext.Transforms.Text.FeaturizeText("Features", nameof(SentimentData.SentimentText))
                .Append(mlContext.BinaryClassification.Trainers.SdcaLogisticRegression(labelColumnName: "Label", featureColumnName: "Features"));

            // 训练模型
            //Console.WriteLine("开始训练模型......");
            var model = pipeline.Fit(dataView);

            // 评估模型
            Console.WriteLine("开始测试评估模型......");
            IDataView predictions = model.Transform(splitDataView.TestSet);
            var metrics = mlContext.BinaryClassification.Evaluate(predictions, "Label");
            Console.WriteLine($"正确度: {metrics.Accuracy:P2}");
            Console.WriteLine($"可信度: {metrics.AreaUnderRocCurve:P2}");
            Console.WriteLine($"F1Score: {metrics.F1Score:P2}");


            var predictionFunction = mlContext.Model.CreatePredictionEngine<SentimentData, SentimentPrediction>(model);

            var sampleStatement = new SentimentData
            {
                SentimentText = "味道很好"
            };


            var resultPrediction = predictionFunction.Predict(sampleStatement);

            Console.WriteLine($"文本: {resultPrediction.SentimentText} | 情感预测: {(resultPrediction.Prediction ? "积极" : "消极")}" +
                $" | 概率: {resultPrediction.Probability} ");
`
这是我的文本
[food.txt](https://github.com/dotnet/docs.zh-cn/files/4647715/food.txt)
