### ISSUE TITLE
描述错误

### ISSUE THREAD

**Issue by Jay-Young** [dotnet/docs.zh-cn#604]
![image](https://user-images.githubusercontent.com/8641055/83012176-a175cf80-a04d-11ea-8c4a-b5447536480e.png)

此处应为 : 

“MM” | 月份（01 到 12）。
-- | --

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [自定义日期和时间格式字符串](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/custom-date-and-time-format-strings?view=netframework-4.8)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @Jay-Young
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@Jay-Young  

感谢你提交的语言方面的反馈。   

遗憾的是，我们语言团队评审你的反馈后，认为它不完全符合我们的接受条件，因为 Translation on current page looks correct. There's no issue in this string.  

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。   

深深的祝福，  
Microsoft DOCS International Team
