### ISSUE TITLE
按照教程里的步骤不能执行

### ISSUE THREAD

**Issue by cnazev** [dotnet/docs.zh-cn#606]
按照教程步骤走下来
在调试部分跟教程里的截图不一致
有一个提示 Open a file which can be debugged or run.
下方的Run and Debug按钮不可用。

另外这篇教程题目是‘使用 Visual Studio Code 在 macOS 中创建 .NET Core 解决方案’
但文章基本跟cli下开发一样，只是在Visual Studio Code的内置终端。
没有提及如何是在Visual Studio Code中打开多项目的解决方案，以及打开解决方案里的项目。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [教程：使用 Visual Studio Code 在 macOS 中创建 .NET Core 解决方案 - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/tutorials/using-on-macos)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @cnazev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18670](https://github.com/dotnet/docs/issues/18670) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18671](https://github.com/dotnet/docs/issues/18671) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@cnazev 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/dotnet/docs/issues/18671。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
