### ISSUE TITLE
「使用主动语态」于翻译之适用性

### ISSUE THREAD

**Issue by liuxilu** [dotnet/docs.zh-cn#608]
> 原文：a reference to the object is passed back to the programmer
> 当前： 创建类的实例后，会将一个该对象的引用传递回程序员
> #594： 创建类的实例后，一个该对象的引用会被传递回程序员
### [这一规则](https://docs.microsoft.com/zh-cn/contribute/dotnet/dotnet-voice-tone#use-active-voice)是否应用于翻译

显然，「active voice is more readable」是基于英文被动句主语在最后造成的（且无主语也无此问题，就像原文），而中文被字句「宾语 被 [主语] 动词 了」是提前了宾语因此不会难读、宾语过长或要强调宾语时反而更可读、若无主语主被动差别仅仅是两个字，所以我认为这一规则不适用于中文翻译，至少部分不适用，不能一刀切。（不是说要合并 #594，这里被字句确不妥，只是说这一规则）

<del>（“未采纳原因: Passive voice should be avoided.” is a passive voice.😂）</del>

**Comment by srvbpigh** [comment]
Hello, @liuxilu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by TakaSoap** [comment]
附议。翻译规则固然重要，但是应该根据实际情况酌情使用，一味地坚持翻译规则而影响可阅读性是本末倒置的。

**Comment by CeciAc** [comment]
你好，@TakaSoap

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/classes

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
