### ISSUE TITLE
「For more infomation, see、有关详细信息，请参阅」的翻译

### ISSUE THREAD

**Issue by liuxilu** [dotnet/docs.zh-cn#610]
[Chinese (Simplified) Style Guide](http://download.microsoft.com/download/4/c/a/4ca95933-3496-4793-9d77-a89b60a8312c/zho-chn-StyleGuide.pdf) 写道：
> choose short word forms and everyday words
> For a more fluent translation, avoid word-to-word translation.

「有关详细信息，请参阅」显然不符合，建议译为「详见」

「For more infomation about XXX, see」则建议译为「XXX 的详细信息见」

如果你们同意，我就开始修改

**Comment by srvbpigh** [comment]
Hello, @liuxilu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by liuxilu** [comment]
还有 see also 另见

**Comment by liuxilu** [comment]
或，关于 XXX 详见

**Comment by liuxilu** [comment]
或直接「XXX 详见」

**Comment by CeciAc** [comment]
你好，@liuxilu
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

**No URL**

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
Hello, @liuxilu

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #612
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
