### ISSUE TITLE
roslyn trivia 译为 末节

### ISSUE THREAD

**Issue by liuxilu** [dotnet/docs.zh-cn#612]
当前有「琐事」和「琐碎内容」两种译法。
 - 「琐事」是「事」，而 trivia 此处不是事，不合适。
 - 「琐碎内容」太啰嗦，「内容」是多余的。
 - 「琐碎」名词性不强，则用「琐屑」。
### 考虑意译而非按词典
- 查朗文得 unimportant or useless details 韦氏得 unimportant matters，文档也说 largely insignificant for normal understanding of the code，那它应该就是 unimportant thing 之意。而「琐」更侧重于碎小而非没用不重要，则用「末节」，虽然是个比喻但极少用本义而不致混淆。

如果你们同意，我就开始修改

**Comment by srvbpigh** [comment]
Hello, @liuxilu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@liuxilu
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

**No URL**

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by liuxilu** [comment]
I'm going to do the modification, and create PRs, so I'm making sure such modifications could be accepted. As the guideline says, "file an issue and start a discussion so we can agree on a direction".
I think it's very clear now. And I wonder whether I should use Chinese or English here, Isn't 如果你们同意，我就开始修改 clear enough? Explanation above applies for #610 #611 as well.

**Comment by liuxilu** [comment]
@CeciAc

**Comment by CeciAc** [comment]
Hello, @liuxilu 

Your contribution is much appreciated. 
As these issues were logged as R, please follow up from there.
For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team

**Comment by liuxilu** [comment]
Sorry I can't understand "duplicate", duplicate of which? Do you mean I should create a PR and discuss there?

**Comment by liuxilu** [comment]
@CeciAc
