### ISSUE TITLE
不应将关键字翻译为中文，应当保留原始的关键字的英文文本。

### ISSUE THREAD

**Issue by JackJCSN** [dotnet/docs.zh-cn#616]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bb2d0d24-a228-ab33-1c62-3b0a701ff318
* Version Independent ID: 9ef3c275-ce7b-808b-8acd-3d394296d897
* Content: [Keywords - Visual Basic](https://docs.microsoft.com/zh-cn/dotnet/visual-basic/language-reference/keywords/)
* Content Source: [docs/visual-basic/language-reference/keywords/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/visual-basic/language-reference/keywords/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @JackJCSN
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@JackJCSN

感谢你的发布内容。

当前不接受有关机器翻译内容的翻译问题的发布内容。

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。

非常感谢你的支持。

Microsoft DOCS 全球体验团队

**Comment by JasonCard** [comment]
Hi @JackJCSN 

Thank you very much for your feedback.
I'll work with the writer to prevent those keywords from being over-localized.
