### ISSUE TITLE
翻译混乱

### ISSUE THREAD

**Issue by Wonderdch** [dotnet/docs.zh-cn#62]
[多态性](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/classes-and-structs/polymorphism)一节中，下面这句翻译混乱。

在此情况下，如果在 D 中使用类型为 D 的变量调用 DoWork``DoWork，被调用的将是新的 。

**Comment by ZSkycat** [comment]
你可以提PR

**Comment by nokura** [comment]
Thank you for your input. Will you please create PR with your suggested correction?
