### ISSUE TITLE
错误的版本描述

### ISSUE THREAD

**Issue by guotiee** [dotnet/docs.zh-cn#646]
此页面有这样一段话：
---开始----
.NET 5 及更高版本
一种跨平台、高性能的开放源 .NET 实现。 包括公共语言运行时 (CLR)、AOT 运行时（正在开发中的 CoreRT）、基类库 (BCL) 以及 .NET SDK。
此 .NET 实现的早期版本称为 .NET Core。 .Net 5.0 是继 .NET Core 3.1 之后的下一版本。 跳过了版本 4，以避免将此较新的 .NET 实现与称为 .NET Framework 的旧实现混淆。 .NET Core 的当前版本为版本 4.8。
请参阅 .NET 基础知识。
---结束---

其中”.NET Core 的当前版本为版本 4.8。“这句话是错误的。应该是：”.Net Framework的当前版本为版本4.8"。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: aa071095-4eb6-20c1-ca26-f34da6fcbdf8
* Version Independent ID: 2b2efd49-b0c8-9a13-525a-d04c802d2bef
* Content: [.NET 术语表](https://docs.microsoft.com/zh-cn/dotnet/standard/glossary)
* Content Source: [docs/standard/glossary.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/glossary.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
"The current version of .NET Core is version 4.8."

That's wrong. It should be: "The current version of the .Net Framework is version 4.8".

**Comment by gewarren** [comment]
@JasonCard I confirmed that the English version shows the correct text, so this is a translation error.

**Comment by JasonCard** [comment]
@guotiee Thank you for your feedback.
@gewarren I agree, this is translation error and will follow up on this.

**Comment by JasonCard** [comment]
Translation is now fixed.
