### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by Zomby7e** [dotnet/docs.zh-cn#662]
From 和 To 居然翻译成了发件人和收件人
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 40d7fd04-e358-9a83-aef2-bfcba1169699
* Version Independent ID: f5df932b-b092-2832-9c9a-61a9c43dcdb3
* Content: [使用 Visual Studio Code 调试 .NET Core 控制台应用程序 - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/tutorials/debugging-with-visual-studio-code)
* Content Source: [docs/core/tutorials/debugging-with-visual-studio-code.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/tutorials/debugging-with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that -- I'm changing the English text so it's less likely to be mistranslated.
