### ISSUE TITLE
词汇错误-映象应该是镜像

### ISSUE THREAD

**Issue by hjkl950217** [dotnet/docs.zh-cn#89]
一般ISO文件叫镜像文件而不是映象文件
images也应该翻译成镜像

**Comment by yufeih** [comment]
你想发个 PR 做这个改进么？

**Comment by imba-tjd** [comment]
Disagree. 微软的说法应该一直是映像，你这样改了，其他所有地方都要改。
![image](https://user-images.githubusercontent.com/24759802/36193137-9f084c30-119f-11e8-8046-b8a93055d88c.png)

**Comment by terrysheng** [comment]
@nokura (to translate imba-tjd's comment into en-us) 
Disagree! Microsoft should always keeps the term as "image". If you make the change now, there will be tons of changes to make.

**Comment by CeciAc** [comment]
@nokura Do you have any update on the status of this issue?

**Comment by hjkl950217** [comment]
但是在文章中，会比较奇怪。。  微软的说法中也有括号注释说这是iso文件

**Comment by ZSkycat** [comment]
我觉得叫映像没有毛病呀

**Comment by CeciAc** [comment]
Hi @nokura 
Please find below our linguist feedback:

> Based on the information available, I think at present, this is still a preferential issue. At least it's not a right-or-wrong issue, it's an acceptance/convention issue.
>  
> Currently, the TS target of "image" is 映像, and that of "mirror" is "镜像" (non-CnE term); thus they can be differentiated from each other. If we adopt the suggestion and do global changes for related terms for consistency, then "镜像" would be the target term for both "image" and "mirror". 
>  
> In practice, if we do some online research on Chinese webpages and documents, we can see "镜像" is quite unanimously used for "mirror", while both "映像" and “镜像” are used for "image".
>     
> In the specific context of ISO image files, 映像 and 镜像 are also used kind of interchangeably on Chinese websites. Indeed "ISO 镜像 " appears more frequently than "ISO 映像", but you can also find the latter in the pages of major IT companies other than Microsoft.  
>  
> From a linguistic point of view, I think there might be a trend towards "ISO 镜像", but it is still evolving, we don't necessarily have to embrace it right now.

**Comment by CeciAc** [comment]
你好，@hjkl950217

感谢你提交的语言方面的反馈。  

遗憾的是，我们语言团队评审你的反馈后，认为它不完全符合我们的接受条件，因为 [LM 应陈述准确原因] 

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福， 
Microsoft DOCS International Team
