### ISSUE TITLE
图片丢失

### ISSUE THREAD

**Issue by Desmond-Liu** [dotnet/docs.zh-cn#99]
https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/tutorials/library-with-visual-studio.md

文档里的图片路径不对， 其他文档也存在同样的问题。

**Comment by Desmond-Liu** [comment]
/docs.zh-cn/tree/live/docs/core/tutorials   
文件夹下缺少 media 文件夹几里面的资源文件

**Comment by yufeih** [comment]
为了减小体积，图片文件会从英文文档里读取，https://github.com/dotnet/docs/blob/live/docs/core/tutorials/library-with-visual-studio.md。最终发布的页面图片会正常显示：https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio

**Comment by nokura** [comment]
This is by design.
